const makeQuiz = (lessonId, quiz) =>
  quiz.map((item, index) => ({
    ...item,
    id: `${lessonId}-q${index + 1}`,
  }));

const makeLesson = (config) => ({
  xp: 100,
  ...config,
  quiz: makeQuiz(config.id, config.quiz),
});

const makeSteps = (first, second, third) => [
  { title: first[0], body: first[1] },
  { title: second[0], body: second[1] },
  { title: third[0], body: third[1] },
];

export const courseModules = [
  {
    id: "fundamentos-logica",
    title: "Fundamentos da lógica",
    level: "Do zero",
    accent: "sunrise",
    summary: "Comece sem depender de linguagem. Primeiro você aprende a pensar, organizar problemas e prever resultados.",
    outcome: "Sair capaz de transformar problemas comuns em passos claros, testáveis e sem ambiguidade.",
    lessons: [
      makeLesson({
        id: "pensamento-computacional",
        title: "Pensamento computacional",
        time: "12 min",
        difficulty: "Nível 1",
        objective: "Entender o que é programar: transformar um problema em uma sequência lógica de decisões.",
        reading: [
          "Programar não começa digitando código. Começa entendendo o problema. Uma pessoa desenvolvedora profissional observa a situação, identifica as entradas, define o resultado esperado e só depois escolhe como implementar.",
          "Pensamento computacional é a habilidade de decompor um problema grande em partes menores, reconhecer padrões, ignorar detalhes que não importam agora e montar uma solução passo a passo.",
          "Sempre pergunte: o que eu recebo, o que preciso decidir, quais regras existem e o que devo entregar no final? Essa pergunta vale para um formulário simples, um app inteiro ou uma API de produção.",
        ],
        concepts: ["Entrada", "Processamento", "Saída", "Decomposição"],
        steps: makeSteps(
          ["Defina o objetivo", "Escreva em uma frase o que precisa ser resolvido antes de pensar em tela ou linguagem."],
          ["Quebre em etapas", "Separe o problema em ações pequenas que uma máquina conseguiria seguir sem adivinhar."],
          ["Valide o final", "Confira se os passos realmente produzem o resultado esperado."],
        ),
        example: {
          label: "Fluxo mental",
          code: [
            "Objetivo: recomendar um filme",
            "Entrada: idade e gênero favorito",
            "Regra: filtrar filmes permitidos para a idade",
            "Saída: mostrar a melhor sugestão",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva o fluxo de um app que recebe um nome e responde com uma saudação personalizada.",
          expected: "A resposta deve separar entrada, processamento e saída sem pular etapas.",
          pitfalls: ["Tentar codar antes de entender", "Confundir interface com regra", "Não definir o resultado final"],
        },
        quiz: [
          {
            question: "Qual é a primeira atitude profissional diante de um problema novo?",
            options: ["Entender entrada, regra e saída", "Escolher um framework", "Copiar um código pronto", "Começar pelo CSS"],
            answer: 0,
            explanation: "Sem entender o fluxo, qualquer código vira tentativa e erro.",
          },
          {
            question: "Decompor um problema significa:",
            options: ["Dividir em partes menores", "Apagar requisitos", "Misturar regras", "Evitar testes"],
            answer: 0,
            explanation: "Problemas menores são mais fáceis de entender, testar e corrigir.",
          },
        ],
      }),
      makeLesson({
        id: "algoritmos-sequencia",
        title: "Algoritmos e sequência",
        time: "12 min",
        difficulty: "Nível 2",
        objective: "Criar instruções em ordem correta, entendendo dependências entre passos.",
        reading: [
          "Um algoritmo é uma sequência de instruções para resolver algo. Ele pode estar escrito em português, pseudocódigo, JavaScript ou outra linguagem. O importante é que cada passo seja claro.",
          "A ordem importa. Não faz sentido mostrar o total de uma compra antes de somar os itens. Também não faz sentido liberar acesso antes de validar email e senha.",
          "Pensar em sequência treina uma habilidade essencial: prever o que o computador sabe em cada momento do fluxo.",
        ],
        concepts: ["Algoritmo", "Sequência", "Dependência", "Ordem de execução"],
        steps: makeSteps(
          ["Liste as ações", "Escreva tudo que precisa acontecer sem se preocupar com código ainda."],
          ["Ordene dependências", "Coloque primeiro os passos que geram dados usados pelos próximos."],
          ["Faça um teste mental", "Leia do começo ao fim e veja se alguma informação aparece antes de existir."],
        ),
        example: {
          label: "Ordem correta",
          code: [
            "Errado:",
            "1. Mostrar total",
            "2. Somar produtos",
            "",
            "Certo:",
            "1. Somar produtos",
            "2. Aplicar desconto",
            "3. Mostrar total",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Organize o fluxo de login: receber dados, validar campos, verificar credenciais, liberar ou negar acesso.",
          expected: "A ordem precisa respeitar dependências e impedir acesso antes da validação.",
          pitfalls: ["Liberar acesso cedo demais", "Validar depois de consultar", "Não tratar erro"],
        },
        quiz: [
          {
            question: "Por que a ordem das instruções importa?",
            options: ["Porque um passo pode depender de outro", "Porque muda a fonte", "Porque elimina variáveis", "Porque substitui backend"],
            answer: 0,
            explanation: "Muitos passos só fazem sentido depois que dados anteriores foram produzidos.",
          },
          {
            question: "Um algoritmo bem escrito deve ser:",
            options: ["Claro, ordenado e testável", "Confuso e curto", "Visual apenas", "Sem regra de saída"],
            answer: 0,
            explanation: "Clareza e ordem tornam a solução verificável.",
          },
        ],
      }),
      makeLesson({
        id: "pseudocodigo-dry-run",
        title: "Pseudocódigo e dry run",
        time: "14 min",
        difficulty: "Nível 3",
        objective: "Escrever lógica antes do código e simular manualmente para encontrar erros cedo.",
        reading: [
          "Pseudocódigo é uma ponte entre ideia e implementação. Ele permite pensar como programador sem travar na sintaxe de uma linguagem específica.",
          "Dry run é executar a lógica manualmente, linha por linha, usando valores de exemplo. É uma técnica simples e muito profissional para encontrar erros antes de abrir o editor.",
          "Quando uma regra fica difícil de explicar em pseudocódigo, provavelmente ela também ficará difícil de manter em código real.",
        ],
        concepts: ["Pseudocódigo", "Simulação manual", "Rastreamento", "Teste de mesa"],
        steps: makeSteps(
          ["Escreva em português estruturado", "Use verbos como receber, validar, calcular, comparar e mostrar."],
          ["Escolha dados de exemplo", "Use valores concretos para testar o fluxo."],
          ["Rastreie resultados", "Anote como cada variável muda até chegar à saída."],
        ),
        example: {
          label: "Teste de mesa",
          code: [
            "receber nota1 = 8",
            "receber nota2 = 6",
            "media <- (nota1 + nota2) / 2",
            "media <- 7",
            "mostrar media",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Escreva um pseudocódigo para calcular idade a partir do ano atual e do ano de nascimento. Depois simule com um exemplo.",
          expected: "A resposta deve ter passos claros e um dry run com números reais.",
          pitfalls: ["Misturar várias linguagens", "Não simular", "Esquecer a saída"],
        },
        quiz: [
          {
            question: "Dry run serve para:",
            options: ["Simular a lógica manualmente", "Escolher cores", "Instalar dependências", "Evitar pensar"],
            answer: 0,
            explanation: "O dry run revela falhas na sequência e nos valores intermediários.",
          },
          {
            question: "Pseudocódigo ajuda porque:",
            options: ["Valida a lógica antes da sintaxe", "Substitui qualquer teste", "Garante deploy", "Remove variáveis"],
            answer: 0,
            explanation: "Ele permite focar no raciocínio antes dos detalhes da linguagem.",
          },
        ],
      }),
      makeLesson({
        id: "entrada-processamento-saida",
        title: "Entrada, processamento e saída",
        time: "13 min",
        difficulty: "Nível 4",
        objective: "Mapear qualquer fluxo como dados recebidos, regras aplicadas e resposta entregue.",
        reading: [
          "Quase todo sistema pode ser entendido como entrada, processamento e saída. A entrada é o que chega: texto, clique, arquivo, API ou banco. O processamento é a regra. A saída é a resposta.",
          "Esse modelo evita confusão porque separa interface de lógica. Um botão bonito não resolve nada sozinho; ele dispara um fluxo que recebe dados e produz consequência.",
          "Profissionais usam esse pensamento para desenhar endpoints, componentes, formulários, validações e fluxos de produto.",
        ],
        concepts: ["Input", "Processamento", "Output", "Regra de negócio"],
        steps: makeSteps(
          ["Identifique a entrada", "Descubra quais dados chegam ao fluxo e de onde eles vêm."],
          ["Defina a regra", "Explique o que o sistema deve fazer com esses dados."],
          ["Descreva a saída", "Determine o que aparece, muda, salva ou retorna no final."],
        ),
        example: {
          label: "Formulário",
          code: [
            "Entrada: email digitado",
            "Processamento: validar formato",
            "Saída: cadastrar ou mostrar erro",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Mapeie entrada, processamento e saída de uma calculadora de IMC.",
          expected: "A resposta precisa citar peso, altura, cálculo e classificação final.",
          pitfalls: ["Ignorar validação", "Falar só da tela", "Não definir resposta final"],
        },
        quiz: [
          {
            question: "Em um formulário, o texto digitado pelo usuário é:",
            options: ["Entrada", "Saída", "Deploy", "Componente"],
            answer: 0,
            explanation: "É o dado que chega ao sistema para ser processado.",
          },
          {
            question: "A regra de negócio fica principalmente em qual parte?",
            options: ["Processamento", "Nome do arquivo", "Cor do botão", "Fonte usada"],
            answer: 0,
            explanation: "O processamento decide o que acontece com a entrada.",
          },
        ],
      }),
    ],
  },
  {
    id: "dados-expressoes",
    title: "Dados e expressões",
    level: "Base forte",
    accent: "ocean",
    summary: "Agora você aprende a guardar informações, escolher tipos, montar cálculos e criar expressões confiáveis.",
    outcome: "Sair sabendo representar dados, comparar valores e evitar erros comuns de tipo e operador.",
    lessons: [
      makeLesson({
        id: "variaveis-tipos",
        title: "Variáveis e tipos de dados",
        time: "14 min",
        difficulty: "Nível 5",
        objective: "Guardar valores com nomes claros e escolher tipos coerentes para cada uso.",
        reading: [
          "Variáveis são nomes que apontam para valores. Elas permitem reutilizar dados e dar significado ao que o programa sabe naquele momento.",
          "Tipos de dados dizem como um valor deve ser interpretado: número para cálculo, texto para palavras, booleano para verdadeiro ou falso, lista para coleções e objeto para entidades.",
          "Nomear bem é parte da lógica. precoFinal explica muito mais que x. Em times profissionais, bons nomes reduzem bugs e aceleram revisão.",
        ],
        concepts: ["Variável", "Número", "Texto", "Booleano", "Nome semântico"],
        steps: makeSteps(
          ["Nomeie pela intenção", "Use nomes que expliquem o papel do dado no fluxo."],
          ["Escolha o tipo certo", "Pense no que será feito com o valor: calcular, comparar, exibir ou agrupar."],
          ["Revise ambiguidade", "Se o nome ou tipo gerar dúvida, ajuste antes de seguir."],
        ),
        example: {
          label: "Variáveis claras",
          code: [
            'nomeCliente <- "Maya"',
            "idadeCliente <- 28",
            "clienteAtivo <- verdadeiro",
            "precoFinal <- 149.90",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Renomeie x, y e z para um fluxo de checkout com preço, cupom e status de pagamento.",
          expected: "Os nomes devem explicar o dado e o tipo esperado.",
          pitfalls: ["Usar abreviações obscuras", "Tratar número como texto", "Criar variável sem necessidade"],
        },
        quiz: [
          {
            question: "Qual nome comunica melhor a intenção?",
            options: ["x", "coisa", "precoFinal", "abc"],
            answer: 2,
            explanation: "precoFinal descreve o papel do valor no fluxo.",
          },
          {
            question: "Booleanos representam:",
            options: ["Verdadeiro ou falso", "Somente textos", "Qualquer imagem", "Pastas do projeto"],
            answer: 0,
            explanation: "Booleanos são usados para decisões lógicas.",
          },
        ],
      }),
      makeLesson({
        id: "operadores-precedencia",
        title: "Operadores e precedência",
        time: "15 min",
        difficulty: "Nível 6",
        objective: "Usar operadores aritméticos, relacionais e lógicos sem gerar resultados inesperados.",
        reading: [
          "Operadores aritméticos calculam, operadores relacionais comparam e operadores lógicos combinam condições. Quase toda regra real usa esses três grupos.",
          "Precedência define o que é avaliado primeiro. Assim como em matemática, multiplicação pode vir antes de soma. Em código, parênteses tornam a intenção explícita.",
          "Uma expressão profissional deve ser correta e legível. Quando a regra fica longa demais, separe partes em variáveis com nomes bons.",
        ],
        concepts: ["Aritmética", "Comparação", "E", "OU", "Precedência"],
        steps: makeSteps(
          ["Escolha o operador", "Decida se precisa calcular, comparar ou combinar condições."],
          ["Use parênteses", "Quando houver dúvida, deixe a ordem explícita."],
          ["Extraia partes", "Regras longas ficam melhores com variáveis auxiliares."],
        ),
        example: {
          label: "Regra legível",
          code: [
            "idadeOk <- idade >= 18",
            "planoOk <- plano = \"pro\"",
            "acessoLiberado <- idadeOk E planoOk",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma expressão para liberar frete grátis quando total >= 200 e cliente estiver ativo.",
          expected: "A resposta deve usar comparação numérica e operador lógico E.",
          pitfalls: ["Trocar E por OU", "Comparar texto com número", "Esquecer parênteses em regra maior"],
        },
        quiz: [
          {
            question: "O operador E exige que:",
            options: ["Todas as condições sejam verdadeiras", "Só uma seja verdadeira", "Nenhuma exista", "A tela esteja carregada"],
            answer: 0,
            explanation: "E representa exigência conjunta.",
          },
          {
            question: "Parênteses ajudam a:",
            options: ["Deixar a ordem de avaliação clara", "Apagar erros automaticamente", "Trocar backend", "Remover variáveis"],
            answer: 0,
            explanation: "Eles tornam a intenção da expressão explícita.",
          },
        ],
      }),
      makeLesson({
        id: "booleanos-tabela-verdade",
        title: "Booleanos e tabela verdade",
        time: "15 min",
        difficulty: "Nível 7",
        objective: "Entender como combinações de verdadeiro e falso controlam decisões reais.",
        reading: [
          "Booleanos parecem simples, mas sustentam autenticação, autorização, validações, filtros e estados de interface.",
          "Tabela verdade é uma forma de visualizar todas as combinações possíveis de uma regra. Ela ajuda a descobrir quando uma decisão está permissiva demais ou rígida demais.",
          "Em regras sensíveis, como acesso admin, pense em todos os cenários: usuário logado, conta ativa, papel correto e recurso permitido.",
        ],
        concepts: ["Verdadeiro", "Falso", "Negação", "Tabela verdade", "Regra composta"],
        steps: makeSteps(
          ["Liste condições", "Escreva cada pergunta booleana separadamente."],
          ["Combine cenários", "Teste o que acontece quando cada condição muda."],
          ["Procure risco", "Veja se alguém recebe permissão quando não deveria."],
        ),
        example: {
          label: "Tabela simples",
          code: [
            "logado | admin | podeExcluir",
            "true   | true  | true",
            "true   | false | false",
            "false  | true  | false",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Monte a tabela verdade para permitir publicar quando contaAtiva e emailVerificado forem verdadeiros.",
          expected: "A resposta deve testar as quatro combinações possíveis.",
          pitfalls: ["Testar só o caso feliz", "Confundir negação", "Usar OU por acidente"],
        },
        quiz: [
          {
            question: "Tabela verdade serve para:",
            options: ["Visualizar combinações lógicas", "Escolher fonte", "Criar commits", "Instalar pacotes"],
            answer: 0,
            explanation: "Ela mostra como cada combinação afeta o resultado final.",
          },
          {
            question: "Negar uma condição significa:",
            options: ["Inverter verdadeiro e falso", "Somar números", "Criar array", "Enviar API"],
            answer: 0,
            explanation: "Negação transforma true em false e false em true.",
          },
        ],
      }),
      makeLesson({
        id: "conversao-validacao-dados",
        title: "Conversão e validação de dados",
        time: "16 min",
        difficulty: "Nível 8",
        objective: "Tratar entradas externas antes de confiar nelas.",
        reading: [
          "Dados que chegam de formulários, URLs, APIs ou bancos podem vir vazios, como texto, nulos, fora do formato ou maliciosos. Um programa profissional nunca confia cegamente na entrada.",
          "Conversão transforma dados para o tipo correto. Validação verifica se o valor existe, tem formato aceitável e respeita a regra do negócio.",
          "Boa validação protege o sistema e melhora a experiência, porque diz exatamente o que precisa ser corrigido.",
        ],
        concepts: ["Parsing", "Formato", "Obrigatoriedade", "Mensagem de erro", "Dado inválido"],
        steps: makeSteps(
          ["Cheque presença", "Verifique se o dado obrigatório realmente chegou."],
          ["Converta com cuidado", "Transforme texto em número ou data antes de operar."],
          ["Responda claramente", "Explique o erro sem expor detalhes internos."],
        ),
        example: {
          label: "Validação",
          code: [
            "se email vazio então mostrar \"Informe seu email\"",
            "se email inválido então mostrar \"Email inválido\"",
            "senão continuar cadastro",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Defina validações para nome, email e senha de um cadastro.",
          expected: "A resposta deve incluir presença, formato e regra mínima de senha.",
          pitfalls: ["Erro genérico", "Validar só um campo", "Operar número como texto"],
        },
        quiz: [
          {
            question: "Validação profissional existe para:",
            options: ["Impedir dados inválidos no fluxo", "Deixar botão maior", "Trocar linguagem", "Remover estados"],
            answer: 0,
            explanation: "Validação protege a lógica e orienta a pessoa usuária.",
          },
          {
            question: "Converter dados é necessário quando:",
            options: ["O tipo recebido não é o tipo usado pela regra", "O layout é escuro", "Não há variável", "O app tem logo"],
            answer: 0,
            explanation: "Exemplo: transformar texto de input em número antes de calcular.",
          },
        ],
      }),
    ],
  },
  {
    id: "decisoes-fluxos",
    title: "Decisões e fluxos reais",
    level: "Básico aplicado",
    accent: "forest",
    summary: "Aqui o programa deixa de ser linear e aprende a reagir a cenários diferentes.",
    outcome: "Sair sabendo criar regras, tratar exceções e modelar estados de produto.",
    lessons: [
      makeLesson({
        id: "if-else",
        title: "If, else e caminhos alternativos",
        time: "14 min",
        difficulty: "Nível 9",
        objective: "Usar condicionais para escolher o caminho correto de execução.",
        reading: [
          "Condicionais permitem que o programa tome decisões. Se uma condição é verdadeira, um bloco executa. Caso contrário, outro caminho pode ser seguido.",
          "A força do if/else está em representar regras de negócio: desconto, acesso, erro, aprovação, exibição de botão, envio de notificação.",
          "A pergunta principal é: qual condição separa um caminho do outro? Se a pergunta estiver confusa, a implementação também ficará.",
        ],
        concepts: ["If", "Else", "Condição", "Caminho alternativo"],
        steps: makeSteps(
          ["Formule a pergunta", "Transforme a regra em uma pergunta que resulte em verdadeiro ou falso."],
          ["Defina consequência", "Explique o que acontece quando a condição passa."],
          ["Trate o contrário", "Decida o que acontece quando a condição falha."],
        ),
        example: {
          label: "Aprovação",
          code: [
            "se media >= 7 então",
            "  mostrar \"Aprovado\"",
            "senão",
            "  mostrar \"Revisar conteúdo\"",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie a regra para aplicar desconto apenas quando o total da compra for maior ou igual a 300.",
          expected: "A resposta deve ter condição, caso verdadeiro e caso falso.",
          pitfalls: ["Não tratar o else", "Usar comparação errada", "Misturar desconto com validação"],
        },
        quiz: [
          {
            question: "If é usado quando o sistema precisa:",
            options: ["Escolher caminho com base em condição", "Trocar fonte", "Criar commit", "Ignorar regra"],
            answer: 0,
            explanation: "Condicionais controlam caminhos alternativos.",
          },
          {
            question: "Else representa:",
            options: ["O caminho quando a condição não passa", "Uma variável numérica", "Uma lista", "Um deploy"],
            answer: 0,
            explanation: "É o comportamento para o cenário contrário.",
          },
        ],
      }),
      makeLesson({
        id: "condicionais-aninhadas",
        title: "Condicionais aninhadas e decisão em camadas",
        time: "15 min",
        difficulty: "Nível 10",
        objective: "Lidar com regras que dependem de mais de uma verificação em sequência.",
        reading: [
          "Nem toda decisão cabe em um único if. Às vezes o sistema precisa validar primeiro se existe dado, depois se o formato é correto, depois se a regra de negócio permite continuar.",
          "Condicionais aninhadas são úteis, mas podem virar labirinto. Profissionais tentam manter o fluxo legível, separando validações e evitando profundidade exagerada.",
          "Quando uma regra começa a ficar difícil de ler, talvez seja hora de quebrar em funções ou usar retornos antecipados.",
        ],
        concepts: ["Aninhamento", "Decisão em camadas", "Fluxo legível", "Profundidade"],
        steps: makeSteps(
          ["Ordene verificações", "Coloque primeiro as condições que bloqueiam o fluxo."],
          ["Evite pirâmide", "Não deixe muitos blocos dentro de blocos sem necessidade."],
          ["Nomeie intenções", "Use variáveis auxiliares para explicar regras compostas."],
        ),
        example: {
          label: "Camadas",
          code: [
            "se email existe então",
            "  se senha existe então",
            "    verificar credenciais",
            "  senão mostrar erro de senha",
            "senão mostrar erro de email",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Desenhe as decisões para permitir compra apenas com usuário logado, carrinho com itens e pagamento aprovado.",
          expected: "A resposta deve respeitar a ordem das verificações.",
          pitfalls: ["Verificar pagamento antes do carrinho", "Criar aninhamento desnecessário", "Não tratar erro específico"],
        },
        quiz: [
          {
            question: "Condicionais aninhadas exigem cuidado porque:",
            options: ["Podem ficar difíceis de ler", "Sempre são proibidas", "Apagam variáveis", "Só funcionam em CSS"],
            answer: 0,
            explanation: "Muita profundidade prejudica manutenção.",
          },
          {
            question: "Uma boa ordem de validação costuma:",
            options: ["Bloquear cedo dados inválidos", "Ignorar erros", "Fazer tudo no final", "Evitar mensagens"],
            answer: 0,
            explanation: "Bloquear cedo evita processamento desnecessário.",
          },
        ],
      }),
      makeLesson({
        id: "guard-clauses",
        title: "Guard clauses e retorno antecipado",
        time: "15 min",
        difficulty: "Nível 11",
        objective: "Simplificar fluxos usando saídas antecipadas para casos inválidos.",
        reading: [
          "Guard clause é uma verificação no início do fluxo que interrompe a execução quando algo não está certo. Ela evita que o código principal fique enterrado dentro de vários ifs.",
          "Essa técnica é muito usada em código profissional porque deixa claro quais condições impedem a ação e qual é o caminho feliz da regra.",
          "Pense assim: primeiro remova os casos que não podem continuar; depois escreva o fluxo principal limpo.",
        ],
        concepts: ["Retorno antecipado", "Caminho feliz", "Bloqueio", "Legibilidade"],
        steps: makeSteps(
          ["Liste bloqueios", "Quais situações impedem o fluxo de continuar?"],
          ["Retorne cedo", "Trate cada bloqueio com uma resposta clara."],
          ["Deixe o principal limpo", "Depois das guards, o restante representa o cenário válido."],
        ),
        example: {
          label: "Guard clause",
          code: [
            "se email vazio então retornar \"Informe o email\"",
            "se senha vazia então retornar \"Informe a senha\"",
            "verificar login",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Use guard clauses para validar uma função que cria tarefa com título obrigatório.",
          expected: "A resposta deve bloquear título vazio antes de criar a tarefa.",
          pitfalls: ["Colocar tudo em um else gigante", "Não retornar mensagem", "Continuar após erro"],
        },
        quiz: [
          {
            question: "Guard clause melhora principalmente:",
            options: ["Leitura do fluxo", "Cor do terminal", "Tamanho do repositório", "Velocidade da internet"],
            answer: 0,
            explanation: "Ela tira casos inválidos do caminho e simplifica o fluxo principal.",
          },
          {
            question: "O caminho feliz é:",
            options: ["O fluxo quando tudo está válido", "Um tema visual", "Um erro de API", "Um arquivo CSS"],
            answer: 0,
            explanation: "É o comportamento principal esperado quando nada bloqueia.",
          },
        ],
      }),
      makeLesson({
        id: "estados-produto",
        title: "Estados: carregando, vazio, erro e sucesso",
        time: "15 min",
        difficulty: "Nível 12",
        objective: "Pensar em fluxos reais que não vivem só do caso feliz.",
        reading: [
          "Iniciantes costumam pensar apenas no cenário ideal. Produtos profissionais tratam carregamento, sucesso, erro, vazio, bloqueado e sem permissão.",
          "Estado é a situação atual do fluxo. Uma tela de lista pode estar carregando dados, vazia, com erro ou exibindo itens. Cada estado precisa de resposta clara.",
          "Quando você modela estados antes de codar, a interface fica previsível e o usuário entende o que está acontecendo.",
        ],
        concepts: ["Loading", "Empty state", "Erro", "Sucesso", "Feedback"],
        steps: makeSteps(
          ["Desenhe o sucesso", "Defina o que acontece quando tudo dá certo."],
          ["Liste falhas", "Pense em erro de rede, dado inválido, lista vazia e permissão negada."],
          ["Dê feedback", "Cada estado precisa orientar a próxima ação."],
        ),
        example: {
          label: "Estados de lista",
          code: [
            "se carregando então mostrar skeleton",
            "se erro então mostrar tentar novamente",
            "se lista vazia então mostrar estado vazio",
            "senão mostrar itens",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Liste estados para uma tela que busca histórico de pedidos.",
          expected: "A resposta deve incluir carregando, erro, vazio e sucesso.",
          pitfalls: ["Pensar só no sucesso", "Não diferenciar vazio de erro", "Não orientar o usuário"],
        },
        quiz: [
          {
            question: "Estado vazio significa:",
            options: ["Não há dados para exibir", "A API sempre falhou", "O app está quebrado", "O CSS sumiu"],
            answer: 0,
            explanation: "Vazio não é necessariamente erro; pode apenas não existir conteúdo ainda.",
          },
          {
            question: "Tratar estados melhora:",
            options: ["Previsibilidade e experiência", "Apenas o nome das pastas", "Nada", "Somente o logo"],
            answer: 0,
            explanation: "Estados claros deixam o produto mais confiável.",
          },
        ],
      }),
    ],
  },
  {
    id: "repeticao-funcoes",
    title: "Repetição, listas e funções",
    level: "Intermediário",
    accent: "ember",
    summary: "Você aprende a repetir ações, percorrer coleções, acumular resultados e dividir lógica em funções.",
    outcome: "Sair capaz de resolver problemas com listas, laços e funções reutilizáveis.",
    lessons: [
      makeLesson({
        id: "loops-for-while",
        title: "Laços: for, while e condição de parada",
        time: "16 min",
        difficulty: "Nível 13",
        objective: "Repetir ações com controle, evitando loops infinitos.",
        reading: [
          "Laços existem para repetir uma ação sem copiar código. Eles aparecem em listas de produtos, notificações, rankings, validações em massa e processamento de dados.",
          "O ponto central não é decorar for ou while. É saber o que se repete, o que muda a cada volta e quando a repetição deve parar.",
          "Todo loop precisa de uma condição de parada alcançável. Sem isso, o programa pode travar ou consumir recursos sem fim.",
        ],
        concepts: ["For", "While", "Iteração", "Condição de parada", "Loop infinito"],
        steps: makeSteps(
          ["Defina o repetido", "Qual ação precisa acontecer várias vezes?"],
          ["Defina o avanço", "Qual valor muda a cada volta?"],
          ["Defina a parada", "Quando o laço deve terminar?"],
        ),
        example: {
          label: "Contagem",
          code: [
            "contador <- 1",
            "enquanto contador <= 5 faça",
            "  mostrar contador",
            "  contador <- contador + 1",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva um laço que mostra os números de 1 a 10.",
          expected: "A resposta deve conter valor inicial, condição e atualização.",
          pitfalls: ["Esquecer atualizar contador", "Não definir parada", "Começar no valor errado"],
        },
        quiz: [
          {
            question: "O que evita loop infinito?",
            options: ["Condição de parada alcançável", "Nome curto", "Tema escuro", "Comentário"],
            answer: 0,
            explanation: "O laço precisa eventualmente deixar de cumprir a condição.",
          },
          {
            question: "Laços são úteis para:",
            options: ["Repetir ações controladas", "Trocar framework", "Remover dados", "Evitar lógica"],
            answer: 0,
            explanation: "Eles automatizam tarefas repetitivas.",
          },
        ],
      }),
      makeLesson({
        id: "arrays-iteracao",
        title: "Arrays e iteração",
        time: "16 min",
        difficulty: "Nível 14",
        objective: "Guardar vários itens e processar cada elemento com segurança.",
        reading: [
          "Arrays são coleções ordenadas. Eles representam listas de tarefas, produtos, alunos, mensagens, commits, notificações e muito mais.",
          "Saber array é saber pensar em conjunto: acessar item por posição, percorrer todos, filtrar alguns, transformar dados e gerar um resultado final.",
          "Um erro comum é escrever lógica pensando em um item só. Profissionais pensam no conjunto e também em lista vazia, item ausente e duplicados.",
        ],
        concepts: ["Array", "Índice", "Item", "Percorrer", "Coleção"],
        steps: makeSteps(
          ["Entenda a lista", "Todos os itens representam o mesmo tipo de entidade?"],
          ["Percorra com regra", "Aplique uma ação a cada elemento."],
          ["Trate extremos", "Pense em lista vazia, tamanho 1 e dados repetidos."],
        ),
        example: {
          label: "Lista",
          code: [
            'alunos <- ["Ana", "Bia", "Caio"]',
            "para cada aluno em alunos faça",
            "  mostrar aluno",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Explique como exibir todos os itens de um carrinho.",
          expected: "A resposta deve citar array, repetição e saída para cada item.",
          pitfalls: ["Pensar só no primeiro item", "Ignorar carrinho vazio", "Não percorrer a lista"],
        },
        quiz: [
          {
            question: "Array é ideal para:",
            options: ["Guardar vários itens relacionados", "Guardar só true ou false", "Substituir if", "Trocar domínio"],
            answer: 0,
            explanation: "Arrays representam coleções.",
          },
          {
            question: "Iterar significa:",
            options: ["Percorrer itens", "Apagar código", "Criar CSS", "Fazer deploy"],
            answer: 0,
            explanation: "Iteração visita os elementos para aplicar uma regra.",
          },
        ],
      }),
      makeLesson({
        id: "acumuladores-contadores",
        title: "Acumuladores, contadores e agregação",
        time: "16 min",
        difficulty: "Nível 15",
        objective: "Construir resultados progressivos durante uma repetição.",
        reading: [
          "Muitos algoritmos percorrem uma lista para produzir um valor final: soma total, quantidade de aprovados, média, maior preço, menor nota, número de erros.",
          "Acumuladores guardam um resultado parcial. Contadores registram quantas vezes algo aconteceu. Ambos precisam de valor inicial, atualização correta e uso final.",
          "Essa lógica é base para relatórios, dashboards, carrinhos, métricas e qualquer produto orientado a dados.",
        ],
        concepts: ["Acumulador", "Contador", "Agregação", "Resultado parcial"],
        steps: makeSteps(
          ["Inicialize", "Comece com zero, lista vazia ou valor neutro adequado."],
          ["Atualize por item", "A cada volta, altere o resultado parcial conforme a regra."],
          ["Use no final", "Depois do laço, o acumulado representa a resposta."],
        ),
        example: {
          label: "Total do carrinho",
          code: [
            "total <- 0",
            "para cada item em carrinho faça",
            "  total <- total + item.preco",
            "mostrar total",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Explique como contar quantos alunos têm nota maior ou igual a 7.",
          expected: "A resposta deve iniciar contador em zero e incrementar quando a condição passar.",
          pitfalls: ["Somar nota em vez de contar", "Não iniciar contador", "Incrementar fora da condição"],
        },
        quiz: [
          {
            question: "Um contador serve para:",
            options: ["Registrar quantidade de ocorrências", "Trocar senha", "Escolher fonte", "Remover arrays"],
            answer: 0,
            explanation: "Ele aumenta conforme eventos ou itens atendem uma regra.",
          },
          {
            question: "Um acumulador normalmente começa com:",
            options: ["Valor neutro", "Qualquer texto", "Erro", "Um botão"],
            answer: 0,
            explanation: "Para soma, o neutro é zero; para lista, pode ser lista vazia.",
          },
        ],
      }),
      makeLesson({
        id: "funcoes-responsabilidade",
        title: "Funções e responsabilidade única",
        time: "17 min",
        difficulty: "Nível 16",
        objective: "Dividir lógica em blocos reutilizáveis, legíveis e testáveis.",
        reading: [
          "Funções encapsulam uma tarefa. Elas recebem entradas, processam e retornam uma saída. Uma boa função tem nome claro e responsabilidade bem definida.",
          "Responsabilidade única significa que a função faz uma coisa principal. calcularFrete é melhor que processarTudoDoPedido, porque é mais fácil de testar e reutilizar.",
          "Funções são uma ponte para código profissional: reduzem duplicação, organizam regras e deixam bugs mais fáceis de localizar.",
        ],
        concepts: ["Função", "Parâmetro", "Retorno", "Reuso", "Responsabilidade única"],
        steps: makeSteps(
          ["Nomeie a ação", "O nome deve dizer o que a função faz."],
          ["Defina entrada e saída", "Quais dados entram? O que retorna?"],
          ["Mantenha foco", "Evite misturar cálculo, validação, UI e persistência na mesma função."],
        ),
        example: {
          label: "Função clara",
          code: [
            "função calcularMedia(nota1, nota2)",
            "  retornar (nota1 + nota2) / 2",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Defina entrada, saída e nome de uma função que calcula desconto por cupom.",
          expected: "A resposta deve separar parâmetros, regra e retorno.",
          pitfalls: ["Função genérica demais", "Sem retorno claro", "Misturar com layout"],
        },
        quiz: [
          {
            question: "Boa função costuma ter:",
            options: ["Nome claro e responsabilidade única", "Nome aleatório", "Várias tarefas misturadas", "Sem entrada"],
            answer: 0,
            explanation: "Isso melhora leitura, teste e manutenção.",
          },
          {
            question: "Parâmetros são:",
            options: ["Dados que entram na função", "Cores da tela", "Pastas", "Commits"],
            answer: 0,
            explanation: "A função usa parâmetros para executar sua regra.",
          },
        ],
      }),
    ],
  },
  {
    id: "estruturas-algoritmos",
    title: "Estruturas e algoritmos",
    level: "Intermediário plus",
    accent: "violet",
    summary: "A lógica sobe de nível: objetos, busca, transformação, ordenação, complexidade e casos limite.",
    outcome: "Sair pensando em dados como estruturas e escolhendo soluções que escalam melhor.",
    lessons: [
      makeLesson({
        id: "objetos-modelagem",
        title: "Objetos e modelagem de domínio",
        time: "16 min",
        difficulty: "Nível 17",
        objective: "Representar entidades reais com atributos coerentes.",
        reading: [
          "Objetos agrupam dados relacionados. Em vez de nomeUsuario, emailUsuario e planoUsuario soltos, você pode modelar um usuário com propriedades.",
          "Modelagem de domínio é entender as coisas importantes do produto: usuário, pedido, lição, pagamento, permissão, tarefa. Bons modelos tornam regras mais claras.",
          "Profissionais não escolhem propriedades aleatoriamente. Cada atributo precisa ter papel na regra, interface, persistência ou integração.",
        ],
        concepts: ["Objeto", "Propriedade", "Entidade", "Domínio", "Modelo"],
        steps: makeSteps(
          ["Identifique a entidade", "Qual coisa do mundo real o sistema representa?"],
          ["Escolha atributos", "Quais dados descrevem essa entidade no produto?"],
          ["Conecte regras", "Que decisões dependem dessas propriedades?"],
        ),
        example: {
          label: "Usuário",
          code: [
            "usuario <- {",
            "  nome: \"Rafa\",",
            "  plano: \"pro\",",
            "  ativo: verdadeiro",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Modele um objeto para representar uma lição da plataforma.",
          expected: "A resposta deve incluir título, nível, duração, status e XP.",
          pitfalls: ["Misturar entidades", "Criar atributo sem uso", "Não pensar em regra"],
        },
        quiz: [
          {
            question: "Objeto é útil para:",
            options: ["Agrupar atributos de uma entidade", "Representar só true", "Substituir todo array", "Trocar deploy"],
            answer: 0,
            explanation: "Objetos organizam dados relacionados.",
          },
          {
            question: "Modelagem boa ajuda a:",
            options: ["Entender melhor o domínio", "Eliminar lógica", "Apagar testes", "Ignorar usuários"],
            answer: 0,
            explanation: "Modelos claros tornam regras mais fáceis de manter.",
          },
        ],
      }),
      makeLesson({
        id: "busca-filtro-transformacao",
        title: "Busca, filtro, map e reduce",
        time: "18 min",
        difficulty: "Nível 18",
        objective: "Selecionar, transformar e resumir coleções.",
        reading: [
          "Grande parte da programação real é manipular listas: buscar um usuário, filtrar pedidos pagos, transformar dados para tela e reduzir uma lista a um total.",
          "Buscar retorna um item ou ausência. Filtrar retorna vários itens que passam na regra. Map transforma cada item. Reduce resume tudo em um valor final.",
          "Mesmo antes de usar métodos de JavaScript, entenda a intenção lógica de cada operação.",
        ],
        concepts: ["Find", "Filter", "Map", "Reduce", "Transformação"],
        steps: makeSteps(
          ["Defina a intenção", "Você quer um item, vários, uma nova lista ou um resumo?"],
          ["Escreva o critério", "O que faz um item entrar no resultado?"],
          ["Valide ausência", "O que acontece se nada for encontrado?"],
        ),
        example: {
          label: "Operações",
          code: [
            "ativos <- filtrar usuários onde ativo = verdadeiro",
            "nomes <- transformar ativos em nome",
            "totalXp <- reduzir usuários somando xp",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Explique como obter apenas tarefas pendentes e mostrar seus títulos.",
          expected: "A resposta deve combinar filtro e transformação.",
          pitfalls: ["Confundir buscar com filtrar", "Não tratar lista vazia", "Misturar regra e saída"],
        },
        quiz: [
          {
            question: "Filtrar significa:",
            options: ["Selecionar itens que passam em uma regra", "Somar tudo sempre", "Pegar só o primeiro sem critério", "Mudar CSS"],
            answer: 0,
            explanation: "Filtro mantém apenas itens relevantes.",
          },
          {
            question: "Reduce é usado para:",
            options: ["Resumir uma coleção em um valor", "Criar botão", "Validar email sempre", "Trocar rota"],
            answer: 0,
            explanation: "Exemplo: somar valores para gerar um total.",
          },
        ],
      }),
      makeLesson({
        id: "ordenacao-comparacao",
        title: "Ordenação e comparação",
        time: "16 min",
        difficulty: "Nível 19",
        objective: "Ordenar dados por critérios claros e comparações consistentes.",
        reading: [
          "Ordenar é colocar itens em uma sequência baseada em critério: preço menor, data mais recente, maior pontuação, prioridade, nome alfabético.",
          "O ponto profissional é escolher o critério correto e deixar previsível o que acontece em empates, valores nulos ou dados inconsistentes.",
          "Ordenação aparece em tabelas, rankings, feeds, histórico, busca e relatórios.",
        ],
        concepts: ["Ordenação", "Critério", "Comparador", "Empate", "Prioridade"],
        steps: makeSteps(
          ["Escolha o campo", "Qual propriedade será usada para ordenar?"],
          ["Defina direção", "Crescente, decrescente, recente, antigo, maior ou menor?"],
          ["Trate empates", "O que acontece quando dois itens têm o mesmo valor?"],
        ),
        example: {
          label: "Ranking",
          code: [
            "ordenar alunos por xp decrescente",
            "se xp igual, ordenar por nome crescente",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Defina a ordenação de uma lista de produtos por preço e depois por avaliação.",
          expected: "A resposta deve ter critério principal e critério de desempate.",
          pitfalls: ["Não definir direção", "Ignorar empate", "Comparar texto como número"],
        },
        quiz: [
          {
            question: "Ordenar exige principalmente:",
            options: ["Critério de comparação", "Um backend", "Uma imagem", "Um commit"],
            answer: 0,
            explanation: "Sem critério, não existe ordem lógica.",
          },
          {
            question: "Empates devem ser tratados porque:",
            options: ["Mantêm resultado previsível", "Removem CSS", "Apagam arrays", "Impedem input"],
            answer: 0,
            explanation: "Critério secundário evita resultados confusos.",
          },
        ],
      }),
      makeLesson({
        id: "complexidade-edge-cases",
        title: "Complexidade e edge cases",
        time: "18 min",
        difficulty: "Nível 20",
        objective: "Avaliar custo da solução e tratar cenários limite.",
        reading: [
          "Uma solução pode funcionar com 5 itens e ficar lenta com 50 mil. Complexidade é pensar no custo da solução quando o volume cresce.",
          "Você não precisa decorar matemática avançada no começo, mas precisa perceber loops desnecessários, buscas repetidas e operações caras dentro de repetições.",
          "Edge cases são cenários limite: lista vazia, dado nulo, item duplicado, valor negativo, permissão ausente, resposta atrasada. Eles separam código amador de produto confiável.",
        ],
        concepts: ["Big O", "Escala", "Custo", "Edge case", "Robustez"],
        steps: makeSteps(
          ["Meça o crescimento", "Pergunte o que acontece quando os dados aumentam muito."],
          ["Procure repetição cara", "Evite repetir trabalho que poderia ser feito uma vez."],
          ["Liste limites", "Teste vazio, nulo, duplicado, ausente e volume alto."],
        ),
        example: {
          label: "Pensamento de escala",
          code: [
            "Cenário A: 10 itens",
            "Cenário B: 100.000 itens",
            "Pergunta: a solução continua aceitável?",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Liste cinco edge cases para buscar produtos em estoque.",
          expected: "Inclua lista vazia, produto inexistente, estoque zero, duplicado e texto inválido.",
          pitfalls: ["Pensar só no caso feliz", "Ignorar volume", "Não tratar ausência"],
        },
        quiz: [
          {
            question: "Complexidade importa porque:",
            options: ["Dados maiores podem tornar a solução ruim", "Troca a cor da tela", "Remove validação", "Cria imagens"],
            answer: 0,
            explanation: "Custo cresce conforme o volume de dados cresce.",
          },
          {
            question: "Edge case é:",
            options: ["Cenário limite que precisa ser tratado", "Um botão", "Um pacote", "Um tema"],
            answer: 0,
            explanation: "Casos limite revelam fragilidades escondidas.",
          },
        ],
      }),
    ],
  },
  {
    id: "javascript-interface",
    title: "JavaScript e interface",
    level: "Avançado aplicado",
    accent: "cobalt",
    summary: "A lógica vira código real no navegador: variáveis, funções, eventos, estado e APIs.",
    outcome: "Sair entendendo como transformar raciocínio em comportamento de tela com JavaScript.",
    lessons: [
      makeLesson({
        id: "traduzindo-para-js",
        title: "Traduzindo lógica para JavaScript",
        time: "18 min",
        difficulty: "Nível 21",
        objective: "Converter pseudocódigo para JS usando const, let, if, arrays e funções.",
        reading: [
          "JavaScript deixa de assustar quando você percebe que a base é a mesma: dados, operadores, condicionais, laços e funções.",
          "A sintaxe muda, mas o raciocínio continua. receber dado vira parâmetro ou input; validar vira if; repetir vira for, map ou loop; retornar resultado vira return.",
          "Profissionais não decoram tudo. Eles entendem o modelo mental e consultam detalhes de sintaxe quando necessário.",
        ],
        concepts: ["const", "let", "if", "return", "Array"],
        steps: makeSteps(
          ["Mapeie o pseudocódigo", "Marque dados, decisões, repetições e saídas."],
          ["Escolha sintaxe JS", "Use const, let, if, for, function ou métodos de array conforme a intenção."],
          ["Teste com exemplos", "Rode mentalmente ou no console com valores reais."],
        ),
        example: {
          label: "JS básico",
          code: [
            "function podeEntrar(idade) {",
            "  return idade >= 18;",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Transforme em JS uma regra que retorna aprovado quando media >= 7.",
          expected: "A resposta deve usar função, parâmetro, comparação e return.",
          pitfalls: ["Esquecer return", "Comparar como texto", "Misturar regra com tela"],
        },
        quiz: [
          {
            question: "return em uma função serve para:",
            options: ["Entregar o resultado da função", "Criar CSS", "Instalar pacote", "Apagar parâmetro"],
            answer: 0,
            explanation: "return devolve a saída do processamento.",
          },
          {
            question: "const é mais indicada quando:",
            options: ["A referência não será reatribuída", "Tudo muda sempre", "Não existe dado", "É CSS"],
            answer: 0,
            explanation: "const comunica intenção de não reatribuir.",
          },
        ],
      }),
      makeLesson({
        id: "dom-eventos",
        title: "DOM, eventos e intenção do usuário",
        time: "18 min",
        difficulty: "Nível 22",
        objective: "Entender como ações da pessoa usuária disparam lógica na interface.",
        reading: [
          "O DOM representa a estrutura da página. Eventos são acontecimentos: clique, digitação, envio de formulário, carregamento, erro, foco.",
          "Toda interface interativa conecta evento a lógica. Um clique não é só visual: ele dispara validação, mudança de estado, chamada de API ou atualização de tela.",
          "O segredo é separar intenção, regra e efeito visual. Isso evita componentes confusos e difíceis de manter.",
        ],
        concepts: ["DOM", "Evento", "Listener", "Formulário", "Efeito"],
        steps: makeSteps(
          ["Identifique o evento", "Qual ação da pessoa dispara o fluxo?"],
          ["Execute a regra", "O que precisa ser validado ou calculado?"],
          ["Atualize a tela", "Qual resposta visual comunica o resultado?"],
        ),
        example: {
          label: "Clique",
          code: [
            "botao.addEventListener('click', () => {",
            "  validarFormulario();",
            "});",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva o fluxo de um botão que salva uma tarefa digitada em um input.",
          expected: "A resposta deve ligar evento, leitura do input, validação e atualização da lista.",
          pitfalls: ["Pensar só no botão", "Não validar vazio", "Não atualizar estado"],
        },
        quiz: [
          {
            question: "Evento é:",
            options: ["Uma ação ou ocorrência capturada pela interface", "Uma variável numérica", "Um banco", "Um deploy"],
            answer: 0,
            explanation: "Eventos disparam comportamentos.",
          },
          {
            question: "Um clique profissionalmente deve ser pensado como:",
            options: ["Início de um fluxo lógico", "Só animação", "Nada", "Arquivo"],
            answer: 0,
            explanation: "A interação inicia regras e efeitos.",
          },
        ],
      }),
      makeLesson({
        id: "estado-ui",
        title: "Estado da tela e UI reativa",
        time: "18 min",
        difficulty: "Nível 23",
        objective: "Modelar dados que controlam o que aparece na interface.",
        reading: [
          "Estado é a memória atual da interface. Se o usuário digitou algo, se a API está carregando, se houve erro ou se a lista tem itens, tudo isso é estado.",
          "UI reativa significa que a tela reflete o estado. Quando o estado muda, a tela deveria mudar de forma previsível.",
          "Saber modelar estado é essencial para front-end moderno, especialmente em React, Vue, Svelte ou qualquer app interativo.",
        ],
        concepts: ["Estado", "Transição", "Renderização", "UI reativa", "Fonte da verdade"],
        steps: makeSteps(
          ["Liste dados visuais", "Quais informações controlam o que aparece?"],
          ["Defina transições", "Que ações mudam esses dados?"],
          ["Evite duplicidade", "Não mantenha o mesmo estado espalhado em vários lugares sem necessidade."],
        ),
        example: {
          label: "Estados",
          code: [
            "estado = 'carregando'",
            "estado = 'sucesso'",
            "estado = 'erro'",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Liste estados de uma tela de quiz com resposta pendente, corrigida, aprovada e revisão.",
          expected: "A resposta deve mostrar como a tela muda em cada estado.",
          pitfalls: ["Confundir estado com cor", "Criar estados duplicados", "Não prever erro"],
        },
        quiz: [
          {
            question: "Estado da UI representa:",
            options: ["Dados que definem o que a tela mostra agora", "Somente CSS", "Nome do repo", "Nada"],
            answer: 0,
            explanation: "A interface é reflexo do estado atual.",
          },
          {
            question: "Transição de estado é:",
            options: ["Mudança de uma situação para outra", "Um arquivo", "Uma fonte", "Um commit"],
            answer: 0,
            explanation: "Exemplo: carregando para sucesso.",
          },
        ],
      }),
      makeLesson({
        id: "assincronia-apis",
        title: "Assincronia, APIs e falhas reais",
        time: "19 min",
        difficulty: "Nível 24",
        objective: "Pensar fluxos que dependem de tempo, rede e resposta externa.",
        reading: [
          "Nem tudo acontece na hora. APIs, bancos, uploads e autenticação dependem de operações assíncronas. Enquanto a resposta não chega, a interface precisa continuar compreensível.",
          "Fluxos assíncronos exigem carregamento, sucesso, erro, cancelamento, retry e proteção contra clique duplicado.",
          "Profissionais modelam o que acontece antes, durante e depois da requisição. Isso evita telas travadas e dados inconsistentes.",
        ],
        concepts: ["Promise", "Loading", "API", "Erro de rede", "Retry"],
        steps: makeSteps(
          ["Dispare a ação", "Identifique o evento que inicia a chamada externa."],
          ["Entre em espera", "Mostre carregamento e bloqueie ações perigosas."],
          ["Trate resposta", "Atualize sucesso, erro ou vazio conforme o retorno."],
        ),
        example: {
          label: "Fluxo API",
          code: [
            "1. Usuário clica em salvar",
            "2. Tela mostra carregando",
            "3. API responde",
            "4. Tela mostra sucesso ou erro",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva a lógica de uma tela que carrega ranking de alunos em uma API.",
          expected: "A resposta deve incluir loading, sucesso, erro, vazio e retry.",
          pitfalls: ["Não tratar falha", "Permitir clique duplicado", "Ignorar carregamento"],
        },
        quiz: [
          {
            question: "Assincronia aparece quando:",
            options: ["A resposta depende de tempo ou serviço externo", "O CSS é escuro", "Não há dados", "Tudo é local sempre"],
            answer: 0,
            explanation: "APIs e bancos geralmente respondem depois.",
          },
          {
            question: "Durante uma chamada de API, a UI precisa:",
            options: ["Comunicar estado de espera", "Fingir que terminou", "Apagar erro", "Ignorar usuário"],
            answer: 0,
            explanation: "Feedback evita confusão e ações repetidas.",
          },
        ],
      }),
    ],
  },
  {
    id: "nivel-profissional",
    title: "Nível profissional",
    level: "Profissional",
    accent: "coral",
    summary: "Fechamento com debug, testes, backend, segurança, arquitetura de fluxo e projeto final.",
    outcome: "Sair pensando como alguém que entrega sistemas confiáveis, testáveis e sustentáveis.",
    lessons: [
      makeLesson({
        id: "debug-logs-metodo",
        title: "Debug, logs e método de investigação",
        time: "18 min",
        difficulty: "Nível 25",
        objective: "Investigar problemas com hipótese, reprodução e evidência.",
        reading: [
          "Debug profissional não é sair mudando tudo. É reproduzir o erro, observar entrada e saída, criar uma hipótese, testar uma mudança por vez e registrar o que foi aprendido.",
          "Logs bons explicam o fluxo sem vazar informação sensível. Eles ajudam a entender onde o sistema entrou, qual decisão tomou e por que falhou.",
          "A diferença entre iniciante e profissional está no método: menos chute, mais evidência.",
        ],
        concepts: ["Reprodução", "Hipótese", "Log", "Causa raiz", "Evidência"],
        steps: makeSteps(
          ["Reproduza o erro", "Encontre um caminho confiável para fazer o problema acontecer."],
          ["Isole variáveis", "Mude uma coisa por vez e observe o impacto."],
          ["Confirme causa", "Só considere resolvido quando a hipótese explicar o problema."],
        ),
        example: {
          label: "Plano de debug",
          code: [
            "1. Qual entrada causou erro?",
            "2. Qual resultado era esperado?",
            "3. Onde o valor ficou incorreto?",
            "4. Qual hipótese explica isso?",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Monte um plano de debug para um login que falha apenas com alguns usuários.",
          expected: "A resposta deve incluir reprodução, comparação de dados e teste de hipótese.",
          pitfalls: ["Mudar tudo ao mesmo tempo", "Não registrar caso que falhou", "Ignorar logs"],
        },
        quiz: [
          {
            question: "Debug profissional começa por:",
            options: ["Reproduzir e entender o erro", "Apagar tudo", "Trocar framework", "Ignorar entrada"],
            answer: 0,
            explanation: "Sem reprodução, a investigação fica sem base.",
          },
          {
            question: "Testar uma hipótese por vez ajuda a:",
            options: ["Encontrar causa real", "Confundir mais", "Apagar logs", "Evitar evidência"],
            answer: 0,
            explanation: "Mudanças isoladas mostram o que realmente alterou o comportamento.",
          },
        ],
      }),
      makeLesson({
        id: "testes-manutencao",
        title: "Testes, manutenção e refatoração",
        time: "19 min",
        difficulty: "Nível 26",
        objective: "Escrever lógica que continue confiável quando o produto evoluir.",
        reading: [
          "Código profissional não precisa apenas funcionar hoje. Ele precisa continuar funcionando quando alguém mexer amanhã. Testes protegem regras importantes contra regressão.",
          "Um teste compara resultado real com resultado esperado. Bons casos incluem limite, erro, valor inválido e cenário comum.",
          "Refatorar é melhorar estrutura sem mudar comportamento. Para refatorar com segurança, você precisa entender a regra e ter formas de verificar se nada quebrou.",
        ],
        concepts: ["Teste", "Regressão", "Caso limite", "Refatoração", "Manutenção"],
        steps: makeSteps(
          ["Escolha comportamento", "Teste regra de negócio, não detalhe visual irrelevante."],
          ["Cubra limites", "Inclua valor abaixo, igual e acima do limite."],
          ["Refatore com segurança", "Melhore nomes e estrutura mantendo resultado igual."],
        ),
        example: {
          label: "Casos de teste",
          code: [
            "freteGratis(199) -> false",
            "freteGratis(200) -> true",
            "freteGratis(250) -> true",
            "freteGratis(null) -> erro controlado",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Liste casos de teste para uma função que calcula desconto VIP.",
          expected: "A resposta deve incluir caso comum, limite, sem VIP e dado inválido.",
          pitfalls: ["Testar só sucesso", "Não testar limite", "Confundir refatoração com mudança de regra"],
        },
        quiz: [
          {
            question: "Teste protege contra:",
            options: ["Regressão", "Qualquer escolha de cor", "Uso de arrays", "Commits"],
            answer: 0,
            explanation: "Regressão é quando algo que funcionava passa a quebrar.",
          },
          {
            question: "Refatorar significa:",
            options: ["Melhorar estrutura sem mudar comportamento", "Apagar regra", "Trocar produto", "Evitar teste"],
            answer: 0,
            explanation: "Refatoração preserva o resultado esperado.",
          },
        ],
      }),
      makeLesson({
        id: "backend-auth-permissoes",
        title: "Backend, autenticação e permissões",
        time: "20 min",
        difficulty: "Nível 27",
        objective: "Modelar fluxos seguros de entrada, regra, persistência e resposta.",
        reading: [
          "No backend, a lógica recebe requisições, valida dados, consulta banco, aplica regra de negócio e devolve resposta estruturada.",
          "Autenticação responde quem é a pessoa. Autorização responde o que essa pessoa pode fazer. Confundir as duas pode gerar falhas graves de segurança.",
          "Profissionais pensam em sucesso, erro, permissão negada, dado inexistente, duplicidade e resposta consistente para quem consome a API.",
        ],
        concepts: ["Backend", "API", "Autenticação", "Autorização", "Persistência"],
        steps: makeSteps(
          ["Receba e valide", "Nunca confie cegamente na requisição."],
          ["Aplique regra segura", "Cheque identidade, permissão e estado do recurso."],
          ["Responda consistente", "Retorne sucesso e erro com formato previsível."],
        ),
        example: {
          label: "Fluxo seguro",
          code: [
            "1. Receber token e dados",
            "2. Confirmar identidade",
            "3. Checar permissão",
            "4. Aplicar regra",
            "5. Salvar e responder",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Desenhe o fluxo para excluir uma tarefa apenas se ela pertencer ao usuário logado.",
          expected: "A resposta deve separar autenticação, busca, autorização, ação e retorno.",
          pitfalls: ["Confiar só no front-end", "Não checar dono do recurso", "Retornar erro confuso"],
        },
        quiz: [
          {
            question: "Autorização responde:",
            options: ["Esta pessoa pode fazer esta ação?", "Qual cor usar?", "Qual fonte?", "Qual commit?"],
            answer: 0,
            explanation: "Autorização controla acesso a ações e recursos.",
          },
          {
            question: "Validar no backend é importante porque:",
            options: ["O front-end pode ser burlado", "CSS sempre falha", "APIs não usam dados", "Remove banco"],
            answer: 0,
            explanation: "Segurança real precisa existir no servidor também.",
          },
        ],
      }),
      makeLesson({
        id: "projeto-final-arquitetura",
        title: "Projeto final: arquitetura de um fluxo real",
        time: "25 min",
        difficulty: "Nível 28",
        objective: "Conectar lógica, UI, API, estado, validação, segurança e testes em uma solução completa.",
        reading: [
          "No nível profissional, você não pensa em blocos isolados. Você desenha jornadas completas: entrada, validação, regra, persistência, estados de tela, erro, sucesso, segurança, logs e testes.",
          "Arquitetura de fluxo é decidir onde cada responsabilidade vive. O front-end coleta e comunica. O estado organiza a tela. A API valida e executa regras. O banco persiste. Testes protegem comportamento.",
          "A meta final é raciocinar como alguém que entrega produto: claro para o usuário, seguro para o negócio e sustentável para a equipe.",
        ],
        concepts: ["Arquitetura", "Fluxo completo", "Responsabilidade", "Qualidade", "Produto"],
        steps: makeSteps(
          ["Desenhe a jornada", "Mapeie antes, durante e depois da ação principal."],
          ["Separe responsabilidades", "Defina o que fica na UI, no estado, na API e no banco."],
          ["Proteja o fluxo", "Inclua validação, permissões, erros, logs e testes."],
        ),
        example: {
          label: "Fluxo completo",
          code: [
            "Projeto: plataforma de lições",
            "1. Usuário responde quiz",
            "2. Front valida campos",
            "3. API corrige e salva progresso",
            "4. UI atualiza XP e próxima lição",
            "5. Testes protegem regras principais",
          ].join("\n"),
        },
        drill: {
          title: "Missão final",
          prompt: "Desenhe a arquitetura do fluxo de uma plataforma que corrige respostas, salva XP e libera novos níveis.",
          expected: "A resposta deve conectar interface, estado, validação, API, banco, erro, permissão e testes.",
          pitfalls: ["Pensar só no visual", "Ignorar erro e segurança", "Não separar responsabilidades", "Não definir testes"],
        },
        quiz: [
          {
            question: "Pensamento profissional aparece quando você:",
            options: ["Enxerga a jornada completa e seus riscos", "Pensa só no botão", "Ignora erro", "Evita validação"],
            answer: 0,
            explanation: "Profissionalismo é conectar regra, produto, segurança e manutenção.",
          },
          {
            question: "Separar responsabilidades ajuda a:",
            options: ["Manter o sistema claro e evolutivo", "Misturar tudo", "Apagar testes", "Ignorar API"],
            answer: 0,
            explanation: "Cada camada fica mais fácil de entender, testar e evoluir.",
          },
        ],
      }),
    ],
  },
];
