const makeQuiz = (lessonId, quiz) =>
  quiz.map((item, index) => ({
    ...item,
    id: `${lessonId}-q${index + 1}`,
  }));

const makeLesson = (config) => ({
  xp: 120,
  ...config,
  quiz: makeQuiz(config.id, config.quiz),
});

const makeSteps = (first, second, third) => [
  { title: first[0], body: first[1] },
  { title: second[0], body: second[1] },
  { title: third[0], body: third[1] },
];

export const courseModules = [
  {
    id: "fundamentos-logica",
    title: "Fundamentos da lógica",
    level: "Do zero",
    accent: "sunrise",
    summary: "Aprenda a pensar como programador antes de depender de sintaxe: entrada, processamento, saída, sequência e teste mental.",
    outcome: "Ao final, você consegue transformar um problema comum em passos claros e escrever seu primeiro algoritmo em JavaScript.",
    lessons: [
      makeLesson({
        id: "pensamento-computacional",
        title: "Pensamento computacional",
        time: "15 min",
        difficulty: "Nível 1",
        objective: "Entender que programar é transformar um problema em passos pequenos, testáveis e sem ambiguidade.",
        reading: [
          "Programar não é decorar comandos. Programar é resolver problemas usando instruções que o computador consegue executar exatamente como foram escritas.",
          "Todo problema pode ser observado por quatro perguntas: quais dados eu recebo, quais regras preciso aplicar, quais decisões existem e qual resultado devo entregar.",
          "Quando você aprende a separar problema, regra e resultado, qualquer linguagem fica menos assustadora. JavaScript vira apenas a ferramenta para escrever a solução.",
        ],
        concepts: ["Problema", "Entrada", "Regra", "Saída", "Decomposição"],
        steps: makeSteps(
          ["Descreva o problema", "Escreva em uma frase simples o que precisa ser resolvido."],
          ["Separe entrada e saída", "Liste o que chega ao programa e o que deve ser mostrado no final."],
          ["Crie passos pequenos", "Cada passo deve ser claro o bastante para outra pessoa seguir sem perguntar nada."],
        ),
        example: {
          label: "Primeiro raciocínio",
          code: [
            "Problema: decidir se uma pessoa pode entrar em um evento.",
            "Entrada: idade.",
            "Regra: idade precisa ser maior ou igual a 18.",
            "Saída: mostrar Pode entrar ou Entrada negada.",
            "",
            "const idade = 18;",
            "const podeEntrar = idade >= 18;",
            "console.log(podeEntrar ? 'Pode entrar' : 'Entrada negada');",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva o fluxo de um app que recebe um nome e mostra uma saudação personalizada. Depois escreva a versão em JavaScript usando const e console.log.",
          expected: "Você deve identificar entrada, processamento e saída, e escrever algo como: const nome = 'Wess'; console.log('Olá, ' + nome).",
          pitfalls: ["Começar pela tela antes da regra", "Não definir a saída", "Tentar decorar sem explicar o fluxo"],
        },
        quiz: [
          {
            question: "Qual é a melhor primeira atitude antes de escrever código?",
            options: ["Entender entrada, regra e saída", "Escolher a cor do botão", "Instalar uma biblioteca", "Copiar uma solução pronta"],
            answer: 0,
            explanation: "Sem entender o fluxo, o código vira tentativa e erro.",
          },
          {
            question: "O que o computador executa melhor?",
            options: ["Instruções claras e ordenadas", "Ideias vagas", "Frases ambíguas", "Regras escondidas"],
            answer: 0,
            explanation: "Computadores não adivinham intenção. Eles seguem instruções explícitas.",
          },
        ],
      }),
      makeLesson({
        id: "algoritmos-sequencia",
        title: "Algoritmos e sequência",
        time: "16 min",
        difficulty: "Nível 2",
        objective: "Criar algoritmos em ordem correta e entender por que um passo depende do anterior.",
        reading: [
          "Um algoritmo é uma sequência de instruções para chegar a um resultado. Ele pode estar em português, pseudocódigo ou JavaScript.",
          "A ordem importa porque o programa só sabe aquilo que já foi criado. Você não consegue mostrar o total antes de calcular o total.",
          "Um bom programador lê o próprio algoritmo de cima para baixo perguntando: neste ponto, quais dados já existem?",
        ],
        concepts: ["Algoritmo", "Sequência", "Dependência", "Ordem de execução"],
        steps: makeSteps(
          ["Liste ações", "Escreva tudo que precisa acontecer sem se preocupar com linguagem."],
          ["Ordene dependências", "Coloque primeiro os passos que produzem dados usados pelos próximos."],
          ["Teste com valores", "Simule o fluxo usando dados reais para ver se a saída faz sentido."],
        ),
        example: {
          label: "Compra com desconto",
          code: [
            "const preco = 100;",
            "const desconto = 20;",
            "const total = preco - desconto;",
            "console.log('Total: R$ ' + total);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie um algoritmo para calcular o preço final de um produto com frete. Escreva em passos e depois em JavaScript.",
          expected: "O preço final deve nascer depois de preço e frete existirem. Exemplo: const total = preco + frete.",
          pitfalls: ["Calcular antes de ter dados", "Misturar nomes", "Mostrar uma variável que não existe"],
        },
        quiz: [
          {
            question: "Por que a ordem das instruções importa?",
            options: ["Porque um passo pode depender do resultado de outro", "Porque deixa o CSS bonito", "Porque elimina testes", "Porque impede usar variáveis"],
            answer: 0,
            explanation: "Se uma variável ainda não existe, os passos seguintes não podem usá-la corretamente.",
          },
          {
            question: "Qual sequência faz mais sentido?",
            options: ["Receber preço, calcular total, mostrar total", "Mostrar total, receber preço, calcular", "Mostrar erro sempre", "Ignorar entrada"],
            answer: 0,
            explanation: "Primeiro chegam os dados, depois vem o cálculo, depois a saída.",
          },
        ],
      }),
      makeLesson({
        id: "entrada-processamento-saida",
        title: "Entrada, processamento e saída",
        time: "16 min",
        difficulty: "Nível 3",
        objective: "Mapear qualquer programa como dados recebidos, regras aplicadas e resposta entregue.",
        reading: [
          "Entrada é tudo que chega ao programa: texto digitado, clique, número, arquivo, resposta de API ou dado do banco.",
          "Processamento é o que o programa faz com a entrada: calcular, validar, comparar, transformar, filtrar ou salvar.",
          "Saída é o resultado: uma mensagem, um valor, uma tela atualizada, um erro ou um dado retornado para outro sistema.",
        ],
        concepts: ["Input", "Processamento", "Output", "Regra de negócio"],
        steps: makeSteps(
          ["Nomeie a entrada", "Defina quais valores o programa precisa receber."],
          ["Escreva a regra", "Explique o que será calculado, validado ou decidido."],
          ["Mostre a saída", "Entregue uma resposta clara para o usuário ou para o sistema."],
        ),
        example: {
          label: "Calculadora de IMC",
          code: [
            "const peso = 70;",
            "const altura = 1.75;",
            "const imc = peso / (altura * altura);",
            "console.log('IMC: ' + imc.toFixed(2));",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma calculadora de média com duas notas. Mostre a média final no console.",
          expected: "Deve existir nota1, nota2, media e console.log com o resultado.",
          pitfalls: ["Dividir antes de somar", "Usar texto no lugar de número", "Não mostrar o resultado"],
        },
        quiz: [
          {
            question: "Em uma calculadora de média, nota1 e nota2 são:",
            options: ["Entradas", "Saídas", "Bibliotecas", "Deploy"],
            answer: 0,
            explanation: "São dados recebidos para o programa processar.",
          },
          {
            question: "A fórmula da média faz parte de qual etapa?",
            options: ["Processamento", "Entrada", "Nome do arquivo", "Estilo visual"],
            answer: 0,
            explanation: "A fórmula é a regra aplicada sobre as entradas.",
          },
        ],
      }),
      makeLesson({
        id: "dry-run-debug",
        title: "Teste de mesa e debug mental",
        time: "18 min",
        difficulty: "Nível 4",
        objective: "Simular o código linha por linha para encontrar erros antes de depender do navegador.",
        reading: [
          "Teste de mesa, ou dry run, é executar mentalmente cada linha do algoritmo anotando o valor das variáveis.",
          "Essa prática transforma erros invisíveis em erros óbvios. Você percebe quando um valor ainda não existe, quando uma conta está errada ou quando uma condição nunca será verdadeira.",
          "Programadores seniores não adivinham bug: eles rastreiam estado. Estado é o conjunto de valores que o programa tem em cada momento.",
        ],
        concepts: ["Dry run", "Estado", "Debug", "Rastreamento"],
        steps: makeSteps(
          ["Escolha valores", "Use números simples para simular o fluxo."],
          ["Leia linha por linha", "Depois de cada linha, anote quais variáveis existem e seus valores."],
          ["Compare com a saída", "Veja se o resultado obtido bate com o resultado esperado."],
        ),
        example: {
          label: "Rastreamento",
          code: [
            "let pontos = 10;        // pontos = 10",
            "pontos = pontos + 5;   // pontos = 15",
            "pontos = pontos * 2;   // pontos = 30",
            "console.log(pontos);   // 30",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Simule manualmente: let saldo = 50; saldo = saldo - 15; saldo = saldo + 30; console.log(saldo). Qual valor aparece?",
          expected: "O valor final deve ser 65, com explicação das mudanças linha por linha.",
          pitfalls: ["Pular linhas", "Não atualizar o valor", "Confundir atribuição com comparação"],
        },
        quiz: [
          {
            question: "Debug mental serve para:",
            options: ["Acompanhar valores linha por linha", "Trocar tema do editor", "Apagar variáveis", "Evitar aprender lógica"],
            answer: 0,
            explanation: "Rastrear valores mostra onde a lógica muda de forma inesperada.",
          },
          {
            question: "Depois de let x = 2; x = x + 3; qual é o valor de x?",
            options: ["5", "2", "3", "23"],
            answer: 0,
            explanation: "O novo valor de x vira o valor antigo, 2, somado com 3.",
          },
        ],
      }),
    ],
  },
  {
    id: "dados-expressoes",
    title: "Dados e expressões",
    level: "Base forte",
    accent: "ocean",
    summary: "Aprenda variáveis, tipos, operadores e expressões para representar informações corretamente.",
    outcome: "Você vai conseguir escrever cálculos, comparações e expressões booleanas usadas em sistemas reais.",
    lessons: [
      makeLesson({
        id: "variaveis-tipos",
        title: "Variáveis e tipos",
        time: "18 min",
        difficulty: "Nível 5",
        objective: "Usar const e let para guardar valores com nomes claros e tipos adequados.",
        reading: [
          "Variáveis dão nome a valores. Bons nomes explicam intenção: precoFinal comunica mais do que x.",
          "Em JavaScript, const é usado quando você não vai trocar o valor da variável. let é usado quando o valor pode mudar durante o fluxo.",
          "Tipos comuns são number, string, boolean, array e object. Escolher o tipo certo evita bugs e deixa o código mais previsível.",
        ],
        concepts: ["const", "let", "number", "string", "boolean"],
        steps: makeSteps(
          ["Escolha bons nomes", "Nomeie pelo significado do dado, não por letras aleatórias."],
          ["Escolha const ou let", "Use const por padrão e let quando o valor mudar."],
          ["Cheque o tipo", "Pergunte se o valor será calculado, exibido, comparado ou agrupado."],
        ),
        example: {
          label: "Tipos básicos",
          code: [
            "const nome = 'Ana';",
            "const idade = 22;",
            "const estaLogado = true;",
            "let pontos = 0;",
            "pontos = pontos + 10;",
            "console.log(nome, idade, estaLogado, pontos);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie variáveis para nome do produto, preço, quantidade e se está em promoção. Mostre uma frase no console.",
          expected: "Use string, number e boolean, com nomes semânticos.",
          pitfalls: ["Usar let sem necessidade", "Nomear como a, b, c", "Colocar número entre aspas quando quer calcular"],
        },
        quiz: [
          {
            question: "Quando usar let?",
            options: ["Quando o valor pode mudar", "Sempre", "Nunca", "Apenas para texto"],
            answer: 0,
            explanation: "let indica que a variável pode receber outro valor depois.",
          },
          {
            question: "Qual nome é mais profissional?",
            options: ["precoFinal", "x", "coisa", "valorzinho"],
            answer: 0,
            explanation: "O nome revela a intenção do dado.",
          },
        ],
      }),
      makeLesson({
        id: "operadores-calculos",
        title: "Operadores e cálculos",
        time: "18 min",
        difficulty: "Nível 6",
        objective: "Usar operadores matemáticos para criar cálculos confiáveis.",
        reading: [
          "Operadores transformam valores. Em JavaScript, + soma, - subtrai, * multiplica, / divide e % retorna o resto da divisão.",
          "Cuidado com textos: '10' + 5 vira '105', porque o sinal de mais também concatena strings.",
          "Em sistemas reais, cálculos aparecem em carrinhos, fretes, descontos, parcelamentos, rankings e métricas.",
        ],
        concepts: ["+", "-", "*", "/", "%", "Precedência"],
        steps: makeSteps(
          ["Garanta números", "Confira se os valores usados no cálculo são number, não string."],
          ["Separe fórmulas", "Use variáveis intermediárias para deixar a conta legível."],
          ["Teste casos simples", "Use valores fáceis para saber se o cálculo está correto."],
        ),
        example: {
          label: "Carrinho simples",
          code: [
            "const preco = 80;",
            "const quantidade = 3;",
            "const desconto = 20;",
            "const subtotal = preco * quantidade;",
            "const total = subtotal - desconto;",
            "console.log('Total: R$ ' + total);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Calcule o total de uma compra com preço, quantidade e frete. Se quiser, adicione desconto.",
          expected: "Use variáveis intermediárias como subtotal e total.",
          pitfalls: ["Misturar string com number", "Fazer uma conta gigante ilegível", "Esquecer quantidade"],
        },
        quiz: [
          {
            question: "O que % retorna?",
            options: ["O resto da divisão", "A porcentagem automática", "Uma string", "Um booleano"],
            answer: 0,
            explanation: "10 % 3 retorna 1, porque sobra 1 na divisão inteira.",
          },
          {
            question: "Qual cálculo representa subtotal de carrinho?",
            options: ["preco * quantidade", "preco - quantidade", "preco == quantidade", "preco && quantidade"],
            answer: 0,
            explanation: "O subtotal é o preço unitário multiplicado pela quantidade.",
          },
        ],
      }),
      makeLesson({
        id: "comparacoes-booleanos",
        title: "Comparações e booleanos",
        time: "18 min",
        difficulty: "Nível 7",
        objective: "Criar expressões que respondem verdadeiro ou falso para tomar decisões.",
        reading: [
          "Booleanos são valores true ou false. Eles são a base das decisões em programação.",
          "Comparações como idade >= 18, senha.length >= 8 e total > 200 retornam booleanos.",
          "Quase toda regra de negócio vira uma pergunta booleana: pode comprar? pode entrar? tem desconto? está válido?",
        ],
        concepts: ["true", "false", ">", "<", ">=", "<=", "===", "!=="],
        steps: makeSteps(
          ["Transforme regra em pergunta", "Exemplo: idade é maior ou igual a 18?"],
          ["Escreva comparação", "Use operadores para produzir true ou false."],
          ["Teste os dois lados", "Teste um valor que passa e outro que falha."],
        ),
        example: {
          label: "Regras booleanas",
          code: [
            "const idade = 20;",
            "const temIngresso = true;",
            "const podeEntrar = idade >= 18 && temIngresso === true;",
            "console.log(podeEntrar);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma regra para frete grátis: total da compra maior ou igual a 200 e cliente logado.",
          expected: "Use comparação e operador lógico &&.",
          pitfalls: ["Usar = no lugar de ===", "Não testar caso falso", "Misturar texto com booleano"],
        },
        quiz: [
          {
            question: "Qual expressão retorna true para idade 18?",
            options: ["idade >= 18", "idade < 18", "idade = 18", "idade !== 18"],
            answer: 0,
            explanation: "Maior ou igual inclui 18.",
          },
          {
            question: "=== serve para:",
            options: ["Comparar valor e tipo", "Atribuir valor", "Criar função", "Somar strings"],
            answer: 0,
            explanation: "Em JavaScript, === é a comparação mais segura para igualdade.",
          },
        ],
      }),
      makeLesson({
        id: "operadores-logicos",
        title: "Operadores lógicos",
        time: "20 min",
        difficulty: "Nível 8",
        objective: "Combinar regras com &&, || e ! para construir decisões reais.",
        reading: [
          "O operador && significa E: todas as condições precisam ser verdadeiras.",
          "O operador || significa OU: basta uma condição ser verdadeira.",
          "O operador ! inverte um booleano. Se estaBloqueado é true, !estaBloqueado é false.",
        ],
        concepts: ["&&", "||", "!", "Composição de regras"],
        steps: makeSteps(
          ["Escreva regras separadas", "Crie variáveis booleanas com nomes claros."],
          ["Combine com intenção", "Use && quando tudo for obrigatório e || quando existir alternativa."],
          ["Leia como frase", "A expressão precisa soar como uma regra humana coerente."],
        ),
        example: {
          label: "Login permitido",
          code: [
            "const emailValido = true;",
            "const senhaValida = true;",
            "const usuarioBloqueado = false;",
            "const podeLogar = emailValido && senhaValida && !usuarioBloqueado;",
            "console.log(podeLogar);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma regra podeComprar: usuário precisa estar logado, carrinho precisa ter itens e pagamento não pode estar bloqueado.",
          expected: "Use três variáveis booleanas e combine com && e !.",
          pitfalls: ["Criar uma expressão gigante sem nomes", "Usar || quando tudo é obrigatório", "Esquecer negação"],
        },
        quiz: [
          {
            question: "Quando usar &&?",
            options: ["Quando todas as regras precisam passar", "Quando qualquer regra basta", "Para somar números", "Para criar objeto"],
            answer: 0,
            explanation: "&& exige que todos os lados sejam verdadeiros.",
          },
          {
            question: "O que !faz com um booleano?",
            options: ["Inverte o valor", "Multiplica", "Transforma em texto", "Cria lista"],
            answer: 0,
            explanation: "!true vira false e !false vira true.",
          },
        ],
      }),
    ],
  },
  {
    id: "controle-fluxo",
    title: "Controle de fluxo",
    level: "Decisões reais",
    accent: "violet",
    summary: "Domine if, else, switch e validações para criar programas que reagem a diferentes cenários.",
    outcome: "Você vai conseguir escrever fluxos de decisão para login, descontos, permissões e mensagens de erro.",
    lessons: [
      makeLesson({
        id: "if-else",
        title: "if, else if e else",
        time: "20 min",
        difficulty: "Nível 9",
        objective: "Tomar decisões no código usando condições claras.",
        reading: [
          "if executa um bloco quando a condição é verdadeira. else executa quando a condição anterior falha.",
          "else if permite testar outra regra antes do else final.",
          "Decisões profissionais precisam ser legíveis. Prefira condições com nomes claros, como clienteElegivel, em vez de misturar tudo dentro do if.",
        ],
        concepts: ["if", "else if", "else", "Fluxo condicional"],
        steps: makeSteps(
          ["Crie a condição", "Transforme a regra em uma expressão booleana."],
          ["Trate sucesso", "Escreva o que acontece quando a regra passa."],
          ["Trate falha", "Escreva mensagens ou caminhos para quando a regra não passa."],
        ),
        example: {
          label: "Classificação de nota",
          code: [
            "const nota = 8;",
            "if (nota >= 7) {",
            "  console.log('Aprovado');",
            "} else if (nota >= 5) {",
            "  console.log('Recuperação');",
            "} else {",
            "  console.log('Reprovado');",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma classificação de idade: criança, adolescente, adulto ou idoso.",
          expected: "Use if, else if e else com faixas coerentes.",
          pitfalls: ["Colocar faixas fora de ordem", "Esquecer else final", "Usar condição impossível"],
        },
        quiz: [
          {
            question: "O else executa quando:",
            options: ["As condições anteriores falham", "O if passa", "Sempre", "A variável é string"],
            answer: 0,
            explanation: "else é o caminho padrão quando nada antes foi verdadeiro.",
          },
          {
            question: "else if serve para:",
            options: ["Testar outra condição", "Declarar variável", "Criar array", "Parar o navegador"],
            answer: 0,
            explanation: "Ele permite criar múltiplos caminhos condicionais.",
          },
        ],
      }),
      makeLesson({
        id: "validacoes-formulario",
        title: "Validações de formulário",
        time: "22 min",
        difficulty: "Nível 10",
        objective: "Validar dados antes de aceitar uma ação do usuário.",
        reading: [
          "Validação é impedir que dados ruins avancem no sistema. Isso protege a experiência e evita erros mais caros depois.",
          "Uma boa validação tem regra, mensagem clara e ordem. Primeiro veja se o campo existe, depois se tem formato correto, depois se atende requisitos.",
          "No front-end, validação melhora UX. No back-end, validação protege o sistema. Em projetos reais, você usa os dois.",
        ],
        concepts: ["Validação", "Mensagem de erro", "Guard clause", "UX"],
        steps: makeSteps(
          ["Valide vazio", "Antes de qualquer regra complexa, veja se o campo foi preenchido."],
          ["Valide formato", "Confira tamanho, caracteres ou padrão esperado."],
          ["Retorne mensagem útil", "Diga exatamente o que o usuário precisa corrigir."],
        ),
        example: {
          label: "Senha mínima",
          code: [
            "const senha = 'abc123';",
            "if (senha.length < 8) {",
            "  console.log('A senha precisa ter pelo menos 8 caracteres.');",
            "} else {",
            "  console.log('Senha válida.');",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Valide um cadastro com nome e senha. Nome não pode estar vazio e senha precisa ter 8 caracteres ou mais.",
          expected: "Use if/else e mensagens específicas para cada erro.",
          pitfalls: ["Mensagem genérica", "Validar senha antes de checar se existe", "Não tratar sucesso"],
        },
        quiz: [
          {
            question: "Por que validar dados?",
            options: ["Para impedir entrada inválida no fluxo", "Para mudar a fonte", "Para evitar usar funções", "Para remover lógica"],
            answer: 0,
            explanation: "Validação evita que o programa processe dados que não fazem sentido.",
          },
          {
            question: "senha.length < 8 testa:",
            options: ["Tamanho da senha", "Cor da senha", "Tipo booleano", "Quantidade de usuários"],
            answer: 0,
            explanation: "length retorna a quantidade de caracteres de uma string.",
          },
        ],
      }),
      makeLesson({
        id: "switch-estados",
        title: "switch e estados",
        time: "18 min",
        difficulty: "Nível 11",
        objective: "Usar switch quando uma variável pode assumir vários estados conhecidos.",
        reading: [
          "switch é útil quando você compara a mesma variável contra vários valores possíveis.",
          "Ele aparece em filtros, status de pedido, níveis de usuário, telas de app e etapas de fluxo.",
          "Use break para impedir que o código continue executando os próximos casos sem querer.",
        ],
        concepts: ["switch", "case", "break", "default", "Estado"],
        steps: makeSteps(
          ["Identifique o estado", "Escolha a variável que representa a situação atual."],
          ["Mapeie casos", "Liste cada valor possível e o que acontece nele."],
          ["Defina default", "Crie um comportamento para valores inesperados."],
        ),
        example: {
          label: "Status de pedido",
          code: [
            "const status = 'pago';",
            "switch (status) {",
            "  case 'pendente':",
            "    console.log('Aguardando pagamento');",
            "    break;",
            "  case 'pago':",
            "    console.log('Preparando envio');",
            "    break;",
            "  default:",
            "    console.log('Status desconhecido');",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie um switch para plano de usuário: free, pro e enterprise. Mostre uma mensagem diferente para cada um.",
          expected: "Use case, break e default.",
          pitfalls: ["Esquecer break", "Não ter default", "Usar switch para comparação complexa demais"],
        },
        quiz: [
          {
            question: "default no switch serve para:",
            options: ["Tratar valor não previsto", "Parar sempre", "Criar variável", "Somar números"],
            answer: 0,
            explanation: "default cobre casos que não bateram com nenhum case.",
          },
          {
            question: "break evita:",
            options: ["Continuar executando próximos cases", "Criar funções", "Comparar strings", "Usar console.log"],
            answer: 0,
            explanation: "Sem break, o fluxo pode cair nos próximos cases.",
          },
        ],
      }),
      makeLesson({
        id: "guard-clauses",
        title: "Guard clauses",
        time: "20 min",
        difficulty: "Nível 12",
        objective: "Escrever validações limpas retornando cedo quando algo está errado.",
        reading: [
          "Guard clause é uma saída antecipada. Você verifica um erro no começo e para o fluxo antes de entrar na lógica principal.",
          "Isso evita ifs gigantes e deixa o caminho feliz mais fácil de ler.",
          "Em funções profissionais, guard clauses aparecem em validações, permissões, formulários e chamadas de API.",
        ],
        concepts: ["Guard clause", "Return antecipado", "Fluxo limpo"],
        steps: makeSteps(
          ["Liste impedimentos", "Quais situações devem bloquear o fluxo?"],
          ["Retorne cedo", "Se algo estiver errado, mostre erro e pare."],
          ["Deixe o sucesso limpo", "Depois das guard clauses, escreva a lógica principal sem aninhamento excessivo."],
        ),
        example: {
          label: "Compra segura",
          code: [
            "function finalizarCompra(total, estaLogado) {",
            "  if (!estaLogado) return 'Faça login para continuar';",
            "  if (total <= 0) return 'Carrinho vazio';",
            "  return 'Compra finalizada';",
            "}",
            "console.log(finalizarCompra(120, true));",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma função podeEnviarFormulario(nome, email). Retorne mensagens de erro se faltar nome ou email. Caso contrário, retorne Enviado.",
          expected: "Use return antecipado para cada erro.",
          pitfalls: ["Criar if dentro de if sem necessidade", "Não retornar mensagem", "Deixar sucesso misturado com erros"],
        },
        quiz: [
          {
            question: "Guard clause melhora o código porque:",
            options: ["Remove caminhos inválidos cedo", "Impede usar return", "Troca JavaScript por CSS", "Apaga validações"],
            answer: 0,
            explanation: "Ela filtra erros antes da lógica principal.",
          },
          {
            question: "Qual é um bom uso de guard clause?",
            options: ["Parar se usuário não está logado", "Somar dois números sempre", "Mudar cor do texto", "Criar HTML"],
            answer: 0,
            explanation: "Permissão é um caso clássico de retorno antecipado.",
          },
        ],
      }),
    ],
  },
  {
    id: "repeticao-colecoes",
    title: "Repetição e coleções",
    level: "Automação",
    accent: "forest",
    summary: "Aprenda loops e arrays para processar listas, somar dados, filtrar itens e automatizar tarefas repetidas.",
    outcome: "Você vai conseguir percorrer listas de produtos, usuários e tarefas usando lógica real.",
    lessons: [
      makeLesson({
        id: "arrays-base",
        title: "Arrays: listas de dados",
        time: "18 min",
        difficulty: "Nível 13",
        objective: "Guardar vários valores em uma lista e acessar itens por índice.",
        reading: [
          "Array é uma lista. Em vez de criar produto1, produto2 e produto3, você cria uma lista de produtos.",
          "Índices começam em zero. O primeiro item está na posição 0, o segundo na posição 1.",
          "Arrays são fundamentais para front-end: menus, cards, produtos, posts, tarefas, comentários e resultados de API quase sempre chegam em lista.",
        ],
        concepts: ["Array", "Índice", "length", "Lista"],
        steps: makeSteps(
          ["Crie a lista", "Agrupe valores relacionados dentro de colchetes."],
          ["Acesse por índice", "Use lista[0] para pegar o primeiro item."],
          ["Conte itens", "Use length para saber quantos elementos existem."],
        ),
        example: {
          label: "Lista de produtos",
          code: [
            "const produtos = ['Mouse', 'Teclado', 'Monitor'];",
            "console.log(produtos[0]);",
            "console.log('Total: ' + produtos.length);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma lista com três tarefas. Mostre a primeira tarefa e a quantidade total.",
          expected: "Use array, índice 0 e length.",
          pitfalls: ["Achar que o primeiro índice é 1", "Criar variáveis soltas", "Esquecer colchetes"],
        },
        quiz: [
          {
            question: "Qual índice pega o primeiro item de um array?",
            options: ["0", "1", "-1", "length"],
            answer: 0,
            explanation: "Arrays em JavaScript começam no índice zero.",
          },
          {
            question: "array.length retorna:",
            options: ["Quantidade de itens", "Primeiro item", "Último item sempre", "Tipo da lista"],
            answer: 0,
            explanation: "length informa o tamanho do array.",
          },
        ],
      }),
      makeLesson({
        id: "for-loop",
        title: "Loop for",
        time: "20 min",
        difficulty: "Nível 14",
        objective: "Executar uma ação várias vezes com controle de início, condição e incremento.",
        reading: [
          "for é usado quando você sabe como controlar a repetição: onde começa, quando para e como avança.",
          "A estrutura tem três partes: inicialização, condição e incremento.",
          "Com for você percorre arrays, gera números, soma totais e cria elementos repetidos na interface.",
        ],
        concepts: ["for", "contador", "incremento", "iteração"],
        steps: makeSteps(
          ["Defina o início", "Normalmente let i = 0."],
          ["Defina a parada", "Exemplo: i < lista.length."],
          ["Atualize o contador", "Use i++ para avançar uma posição."],
        ),
        example: {
          label: "Percorrendo lista",
          code: [
            "const tarefas = ['Estudar', 'Praticar', 'Revisar'];",
            "for (let i = 0; i < tarefas.length; i++) {",
            "  console.log((i + 1) + '. ' + tarefas[i]);",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Percorra uma lista de nomes e mostre Olá, nome para cada pessoa.",
          expected: "Use for, i < nomes.length e nomes[i].",
          pitfalls: ["Usar <= e acessar posição inexistente", "Esquecer i++", "Não usar o item atual"],
        },
        quiz: [
          {
            question: "Em i < lista.length, a condição serve para:",
            options: ["Parar antes de sair da lista", "Criar uma string", "Somar itens", "Remover o array"],
            answer: 0,
            explanation: "Isso evita acessar índices que não existem.",
          },
          {
            question: "i++ significa:",
            options: ["Aumentar i em 1", "Diminuir i em 1", "Comparar i", "Apagar i"],
            answer: 0,
            explanation: "É o incremento comum em loops.",
          },
        ],
      }),
      makeLesson({
        id: "somar-filtrar-listas",
        title: "Somar e filtrar listas",
        time: "22 min",
        difficulty: "Nível 15",
        objective: "Processar listas para calcular totais e selecionar itens que atendem regras.",
        reading: [
          "Muitos sistemas existem para processar listas: somar carrinho, filtrar produtos, contar usuários ativos, encontrar tarefas pendentes.",
          "Para somar, você cria uma variável acumuladora e adiciona valores durante o loop.",
          "Para filtrar, você testa uma condição em cada item e guarda apenas os que passam.",
        ],
        concepts: ["Acumulador", "Filtro", "Lista processada", "Condição por item"],
        steps: makeSteps(
          ["Crie acumulador", "Use let total = 0 para somar valores."],
          ["Percorra a lista", "Passe por cada item com for."],
          ["Aplique regra", "Some, conte ou guarde apenas itens válidos."],
        ),
        example: {
          label: "Total do carrinho",
          code: [
            "const precos = [30, 50, 20];",
            "let total = 0;",
            "for (let i = 0; i < precos.length; i++) {",
            "  total = total + precos[i];",
            "}",
            "console.log('Total: ' + total);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Some uma lista de notas e calcule a média final.",
          expected: "Use acumulador total, loop e depois divida por notas.length.",
          pitfalls: ["Dividir dentro do loop sem necessidade", "Esquecer let total", "Não usar length"],
        },
        quiz: [
          {
            question: "Um acumulador serve para:",
            options: ["Guardar resultado progressivo", "Criar CSS", "Parar função", "Apagar lista"],
            answer: 0,
            explanation: "Ele guarda uma soma ou contagem enquanto o loop avança.",
          },
          {
            question: "Para filtrar itens, você precisa de:",
            options: ["Uma condição por item", "Um deploy", "Uma imagem", "Um console vazio"],
            answer: 0,
            explanation: "Cada item precisa ser testado contra uma regra.",
          },
        ],
      }),
      makeLesson({
        id: "metodos-array",
        title: "map, filter e reduce",
        time: "25 min",
        difficulty: "Nível 16",
        objective: "Usar métodos modernos de array para transformar, filtrar e reduzir listas.",
        reading: [
          "map transforma cada item e devolve uma nova lista do mesmo tamanho.",
          "filter mantém apenas itens que passam em uma condição.",
          "reduce reduz a lista a um único resultado, como soma, média, objeto agrupado ou total calculado.",
        ],
        concepts: ["map", "filter", "reduce", "callback"],
        steps: makeSteps(
          ["Use map para transformar", "Quando cada item vira outra versão dele."],
          ["Use filter para selecionar", "Quando alguns itens entram e outros ficam fora."],
          ["Use reduce para resumir", "Quando a lista vira um único valor final."],
        ),
        example: {
          label: "Produtos em promoção",
          code: [
            "const produtos = [",
            "  { nome: 'Mouse', preco: 80 },",
            "  { nome: 'Monitor', preco: 900 },",
            "];",
            "const nomes = produtos.map((produto) => produto.nome);",
            "const caros = produtos.filter((produto) => produto.preco > 100);",
            "const total = produtos.reduce((soma, produto) => soma + produto.preco, 0);",
            "console.log(nomes, caros, total);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Com uma lista de tarefas, use filter para pegar pendentes e map para mostrar só os títulos.",
          expected: "Use objetos com title e done, depois filter e map.",
          pitfalls: ["Alterar lista original sem querer", "Confundir map com filter", "Esquecer return implícito"],
        },
        quiz: [
          {
            question: "filter retorna:",
            options: ["Uma nova lista com itens aprovados", "Um único número sempre", "Uma string", "Nada"],
            answer: 0,
            explanation: "filter mantém itens que retornam true na condição.",
          },
          {
            question: "reduce é bom para:",
            options: ["Gerar um valor final a partir da lista", "Criar CSS", "Renderizar imagem", "Declarar variável apenas"],
            answer: 0,
            explanation: "reduce resume uma lista em um resultado acumulado.",
          },
        ],
      }),
    ],
  },
  {
    id: "funcoes-modularizacao",
    title: "Funções e organização",
    level: "Código reutilizável",
    accent: "amber",
    summary: "Aprenda a criar funções pequenas, reutilizáveis e fáceis de testar.",
    outcome: "Você vai conseguir transformar regras soltas em funções reutilizáveis para projetos reais.",
    lessons: [
      makeLesson({
        id: "funcoes-base",
        title: "Funções na prática",
        time: "20 min",
        difficulty: "Nível 17",
        objective: "Criar funções com parâmetro, retorno e responsabilidade clara.",
        reading: [
          "Função é um bloco reutilizável de lógica. Ela recebe dados, processa e devolve resultado.",
          "Parâmetros são entradas da função. return é a saída da função.",
          "Uma função boa faz uma coisa bem feita. Se o nome precisa de 'e', talvez ela esteja fazendo mais de uma responsabilidade.",
        ],
        concepts: ["function", "parâmetro", "return", "responsabilidade"],
        steps: makeSteps(
          ["Nomeie a ação", "Use verbos como calcular, validar, formatar ou buscar."],
          ["Defina parâmetros", "Quais dados a função precisa receber?"],
          ["Retorne resultado", "Evite depender apenas de console.log dentro da função."],
        ),
        example: {
          label: "Função pura",
          code: [
            "function calcularMedia(nota1, nota2) {",
            "  return (nota1 + nota2) / 2;",
            "}",
            "const media = calcularMedia(8, 6);",
            "console.log(media);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma função calcularDesconto(preco, desconto) que retorne o preço final.",
          expected: "A função deve receber dois parâmetros e usar return.",
          pitfalls: ["Fixar valores dentro da função", "Usar console.log no lugar de return", "Nome genérico"],
        },
        quiz: [
          {
            question: "Parâmetros são:",
            options: ["Entradas da função", "Saídas do CSS", "Erros do navegador", "Arquivos"],
            answer: 0,
            explanation: "Eles permitem chamar a mesma função com valores diferentes.",
          },
          {
            question: "return serve para:",
            options: ["Devolver um resultado", "Criar HTML", "Pintar botão", "Apagar array"],
            answer: 0,
            explanation: "return entrega o valor calculado pela função.",
          },
        ],
      }),
      makeLesson({
        id: "escopo-imutabilidade",
        title: "Escopo e imutabilidade",
        time: "20 min",
        difficulty: "Nível 18",
        objective: "Entender onde variáveis existem e evitar mudanças perigosas de estado.",
        reading: [
          "Escopo define onde uma variável pode ser acessada. Variáveis criadas dentro de uma função não existem fora dela.",
          "Imutabilidade é preferir criar novos valores em vez de alterar dados existentes sem controle.",
          "Em React e front-end moderno, imutabilidade é essencial para atualizar telas de forma previsível.",
        ],
        concepts: ["Escopo", "Estado", "Imutabilidade", "Previsibilidade"],
        steps: makeSteps(
          ["Crie variáveis perto do uso", "Evite variáveis globais sem necessidade."],
          ["Retorne novos valores", "Não altere dados externos quando puder devolver um resultado novo."],
          ["Teste isolamento", "A função deve funcionar sem depender de valores escondidos."],
        ),
        example: {
          label: "Sem efeito colateral",
          code: [
            "function adicionarItem(lista, item) {",
            "  return [...lista, item];",
            "}",
            "const tarefas = ['Estudar'];",
            "const novasTarefas = adicionarItem(tarefas, 'Praticar');",
            "console.log(novasTarefas);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma função concluirTarefa(tarefa) que devolve uma nova tarefa com done: true.",
          expected: "Use spread de objeto: return { ...tarefa, done: true }.",
          pitfalls: ["Alterar o objeto original", "Esquecer return", "Usar variável fora do escopo"],
        },
        quiz: [
          {
            question: "Escopo define:",
            options: ["Onde uma variável pode ser usada", "O tamanho da tela", "A cor do app", "A versão do Vite"],
            answer: 0,
            explanation: "Variáveis existem dentro de determinados blocos ou funções.",
          },
          {
            question: "Imutabilidade ajuda porque:",
            options: ["Torna mudanças mais previsíveis", "Impede usar arrays", "Remove funções", "Apaga estado"],
            answer: 0,
            explanation: "Criar novos valores reduz efeitos colaterais inesperados.",
          },
        ],
      }),
      makeLesson({
        id: "objetos-modelagem",
        title: "Objetos e modelagem",
        time: "22 min",
        difficulty: "Nível 19",
        objective: "Representar entidades reais com objetos e acessar propriedades.",
        reading: [
          "Objeto agrupa informações relacionadas. Um usuário pode ter nome, email e plano. Um produto pode ter nome, preço e estoque.",
          "Modelar bem é escolher propriedades que representam o negócio sem exagerar.",
          "Front-end trabalha com objetos o tempo todo: props, respostas de API, estado local e dados renderizados em cards.",
        ],
        concepts: ["Objeto", "Propriedade", "Modelagem", "Entidade"],
        steps: makeSteps(
          ["Identifique a entidade", "Pergunte qual coisa real você está representando."],
          ["Escolha propriedades", "Liste apenas informações necessárias para o fluxo."],
          ["Acesse dados", "Use objeto.propriedade para ler valores."],
        ),
        example: {
          label: "Produto",
          code: [
            "const produto = {",
            "  nome: 'Teclado',",
            "  preco: 150,",
            "  estoque: 8,",
            "};",
            "console.log(produto.nome + ' custa R$ ' + produto.preco);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie um objeto usuario com nome, idade e plano. Mostre uma frase com esses dados.",
          expected: "Use objeto com propriedades e acesse com ponto.",
          pitfalls: ["Criar variáveis soltas", "Usar nomes sem sentido", "Esquecer vírgulas no objeto"],
        },
        quiz: [
          {
            question: "Objeto serve para:",
            options: ["Agrupar dados relacionados", "Repetir código", "Parar loop", "Criar CSS"],
            answer: 0,
            explanation: "Objetos representam entidades com propriedades.",
          },
          {
            question: "produto.preco acessa:",
            options: ["A propriedade preco", "O array inteiro", "Uma função global", "O HTML"],
            answer: 0,
            explanation: "A notação com ponto lê uma propriedade do objeto.",
          },
        ],
      }),
      makeLesson({
        id: "composicao-funcoes",
        title: "Composição de funções",
        time: "24 min",
        difficulty: "Nível 20",
        objective: "Montar soluções maiores combinando funções pequenas.",
        reading: [
          "Código profissional raramente é uma função gigante. Ele é composto por pequenas funções com nomes claros.",
          "Composição significa usar o resultado de uma função como entrada de outra.",
          "Isso facilita teste, manutenção e leitura. Se uma regra muda, você ajusta uma parte pequena do fluxo.",
        ],
        concepts: ["Composição", "Função pequena", "Pipeline", "Manutenção"],
        steps: makeSteps(
          ["Separe responsabilidades", "Uma função calcula, outra valida, outra formata."],
          ["Conecte retornos", "Use o resultado de uma função na próxima etapa."],
          ["Teste partes", "Valide cada função sozinha antes de testar o fluxo completo."],
        ),
        example: {
          label: "Fluxo de compra",
          code: [
            "function calcularSubtotal(preco, quantidade) {",
            "  return preco * quantidade;",
            "}",
            "function aplicarDesconto(valor) {",
            "  return valor >= 200 ? valor - 20 : valor;",
            "}",
            "const subtotal = calcularSubtotal(80, 3);",
            "const total = aplicarDesconto(subtotal);",
            "console.log(total);",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie duas funções: calcularMedia e verificarAprovacao. Use a primeira dentro do fluxo da segunda.",
          expected: "A solução deve ter funções pequenas e retorno claro.",
          pitfalls: ["Fazer tudo em uma função gigante", "Não retornar valores", "Misturar cálculo com mensagem sem pensar"],
        },
        quiz: [
          {
            question: "Compor funções significa:",
            options: ["Combinar funções pequenas em um fluxo", "Criar um arquivo enorme", "Evitar return", "Usar apenas console.log"],
            answer: 0,
            explanation: "Soluções maiores podem ser montadas com funções menores.",
          },
          {
            question: "Uma função pequena é melhor porque:",
            options: ["É mais fácil de testar e manter", "Sempre roda sem erro", "Remove variáveis", "Dispensa lógica"],
            answer: 0,
            explanation: "Responsabilidade clara facilita manutenção.",
          },
        ],
      }),
    ],
  },
  {
    id: "dom-projetos",
    title: "DOM e projetos práticos",
    level: "Front-end real",
    accent: "rose",
    summary: "Leve sua lógica para a tela: eventos, DOM, formulários e renderização de listas.",
    outcome: "Você vai conseguir criar interações reais no navegador com JavaScript.",
    lessons: [
      makeLesson({
        id: "dom-selecao-eventos",
        title: "DOM, seleção e eventos",
        time: "24 min",
        difficulty: "Nível 21",
        objective: "Selecionar elementos da página e responder a cliques do usuário.",
        reading: [
          "DOM é a representação da página que o JavaScript consegue ler e alterar.",
          "Com querySelector você seleciona elementos. Com addEventListener você reage a ações como click, input e submit.",
          "A lógica continua a mesma: evento é entrada, função é processamento, mudança na tela é saída.",
        ],
        concepts: ["DOM", "querySelector", "addEventListener", "Evento"],
        steps: makeSteps(
          ["Selecione elementos", "Pegue botão, input ou área de resultado."],
          ["Escute evento", "Use addEventListener para reagir ao usuário."],
          ["Atualize a tela", "Altere textContent, classList ou valores exibidos."],
        ),
        example: {
          label: "Clique simples",
          code: [
            "const botao = document.querySelector('#botao');",
            "const resultado = document.querySelector('#resultado');",
            "botao.addEventListener('click', () => {",
            "  resultado.textContent = 'Você clicou!';",
            "});",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie um botão que aumenta um contador na tela a cada clique.",
          expected: "Use variável contador, addEventListener e textContent.",
          pitfalls: ["Selecionar id errado", "Criar contador dentro do clique sem querer", "Não atualizar a tela"],
        },
        quiz: [
          {
            question: "addEventListener serve para:",
            options: ["Ouvir ações do usuário", "Criar banco de dados", "Trocar deploy", "Somar arrays"],
            answer: 0,
            explanation: "Ele conecta eventos da interface a funções JavaScript.",
          },
          {
            question: "textContent altera:",
            options: ["Texto de um elemento", "O nome do arquivo", "O terminal", "A versão do React"],
            answer: 0,
            explanation: "É uma forma segura de mudar texto visível na página.",
          },
        ],
      }),
      makeLesson({
        id: "formularios",
        title: "Formulários interativos",
        time: "24 min",
        difficulty: "Nível 22",
        objective: "Ler valores de inputs, validar e mostrar mensagens na tela.",
        reading: [
          "Formulários são uma das partes mais importantes do front-end. Eles capturam dados e disparam regras.",
          "O evento submit permite controlar o envio. preventDefault impede recarregar a página.",
          "Validação boa mostra mensagens específicas e ajuda o usuário a corrigir o erro.",
        ],
        concepts: ["form", "input", "submit", "preventDefault", "value"],
        steps: makeSteps(
          ["Capture submit", "Escute o envio do formulário."],
          ["Leia valores", "Use input.value para pegar o que foi digitado."],
          ["Valide e responda", "Mostre sucesso ou erro sem recarregar a página."],
        ),
        example: {
          label: "Cadastro simples",
          code: [
            "form.addEventListener('submit', (event) => {",
            "  event.preventDefault();",
            "  const nome = inputNome.value.trim();",
            "  if (!nome) {",
            "    mensagem.textContent = 'Digite seu nome.';",
            "    return;",
            "  }",
            "  mensagem.textContent = 'Bem-vindo, ' + nome;",
            "});",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma validação de email: se estiver vazio, mostre erro; se tiver @, mostre sucesso.",
          expected: "Use submit, preventDefault, value, includes('@') e mensagens.",
          pitfalls: ["Deixar página recarregar", "Não usar trim", "Mensagem genérica demais"],
        },
        quiz: [
          {
            question: "preventDefault em submit evita:",
            options: ["Recarregar a página automaticamente", "Usar input", "Criar função", "Mostrar texto"],
            answer: 0,
            explanation: "Assim você controla o fluxo com JavaScript.",
          },
          {
            question: "input.value retorna:",
            options: ["Valor digitado", "Texto do botão sempre", "Array de usuários", "CSS do input"],
            answer: 0,
            explanation: "É como ler o conteúdo atual do campo.",
          },
        ],
      }),
      makeLesson({
        id: "renderizar-listas",
        title: "Renderizar listas na tela",
        time: "25 min",
        difficulty: "Nível 23",
        objective: "Transformar arrays em elementos visuais usando JavaScript.",
        reading: [
          "Renderizar é transformar dados em interface. Uma lista de produtos vira cards. Uma lista de tarefas vira itens na tela.",
          "O segredo é não escrever HTML repetido manualmente. Você percorre os dados e cria a marcação a partir deles.",
          "Isso prepara você para React, onde renderizar listas com map é uma rotina diária.",
        ],
        concepts: ["Renderização", "Template", "innerHTML", "map"],
        steps: makeSteps(
          ["Tenha dados em array", "A interface nasce dos dados."],
          ["Transforme em HTML", "Use map para criar uma string de marcação."],
          ["Insira no container", "Mostre o resultado na tela."],
        ),
        example: {
          label: "Cards de produtos",
          code: [
            "const produtos = ['Mouse', 'Teclado'];",
            "lista.innerHTML = produtos",
            "  .map((produto) => `<li>${produto}</li>`)",
            "  .join('');",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Crie uma lista de tarefas e renderize cada tarefa como li dentro de uma ul.",
          expected: "Use array, map, join e innerHTML.",
          pitfalls: ["Esquecer join", "Misturar lógica e dados demais", "Renderizar string com vírgulas"],
        },
        quiz: [
          {
            question: "Renderizar lista significa:",
            options: ["Transformar dados em elementos visuais", "Apagar array", "Fazer deploy", "Criar servidor"],
            answer: 0,
            explanation: "Dados viram interface visível para o usuário.",
          },
          {
            question: "Por que usar join após map para HTML?",
            options: ["Para unir a lista em uma string sem vírgulas", "Para deletar itens", "Para validar email", "Para parar evento"],
            answer: 0,
            explanation: "map retorna array; join transforma em string final.",
          },
        ],
      }),
      makeLesson({
        id: "mini-projeto-todo",
        title: "Mini projeto: To-do list",
        time: "30 min",
        difficulty: "Nível 24",
        objective: "Construir uma lista de tarefas simples com adicionar, renderizar e concluir.",
        reading: [
          "Um to-do app parece simples, mas ensina quase tudo: dados, eventos, funções, arrays, objetos, estado e renderização.",
          "O estado principal é uma lista de tarefas. Cada ação altera essa lista e renderiza a tela novamente.",
          "Esse padrão é a base de apps front-end modernos: estado muda, interface atualiza.",
        ],
        concepts: ["Estado", "CRUD simples", "Renderização", "Evento"],
        steps: makeSteps(
          ["Crie o estado", "Use uma lista de objetos com title e done."],
          ["Adicione tarefa", "No submit, crie novo objeto e atualize a lista."],
          ["Renderize novamente", "Toda mudança deve chamar uma função render."],
        ),
        example: {
          label: "Estado de tarefas",
          code: [
            "let tarefas = [];",
            "function adicionarTarefa(titulo) {",
            "  tarefas = [...tarefas, { titulo, done: false }];",
            "  renderizar();",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Monte a lógica de um to-do: array tarefas, função adicionarTarefa e função listarTarefas no console.",
          expected: "Você deve criar estado, função de adição e função para mostrar tarefas.",
          pitfalls: ["Criar tarefa sem título", "Não atualizar lista", "Misturar estado com HTML sem controle"],
        },
        quiz: [
          {
            question: "No to-do, a lista de tarefas representa:",
            options: ["Estado da aplicação", "CSS global", "Deploy", "Erro"],
            answer: 0,
            explanation: "Estado é a memória atual da interface.",
          },
          {
            question: "Depois de alterar o estado, normalmente você precisa:",
            options: ["Renderizar a tela novamente", "Fechar o navegador", "Apagar funções", "Mudar linguagem"],
            answer: 0,
            explanation: "A interface precisa refletir o novo estado.",
          },
        ],
      }),
    ],
  },
  {
    id: "react-preparacao",
    title: "Preparação para React",
    level: "Próximo passo",
    accent: "blue",
    summary: "Entenda os conceitos que tornam React mais fácil: componentes, props, estado e renderização declarativa.",
    outcome: "Você vai sair pronto para entender componentes React sem decorar código vazio.",
    lessons: [
      makeLesson({
        id: "componentes-mentalidade",
        title: "Mentalidade de componentes",
        time: "22 min",
        difficulty: "Nível 25",
        objective: "Dividir uma interface em partes pequenas e reutilizáveis.",
        reading: [
          "Componente é uma parte da interface com responsabilidade própria: botão, card, header, lista, formulário.",
          "Antes de aprender React, treine enxergar telas como peças. Isso reduz complexidade e melhora organização.",
          "Um bom componente tem nome claro, recebe dados e renderiza uma parte previsível da interface.",
        ],
        concepts: ["Componente", "Responsabilidade", "Reuso", "UI"],
        steps: makeSteps(
          ["Observe a tela", "Identifique blocos repetidos ou independentes."],
          ["Nomeie componentes", "Use nomes como ProductCard, Header ou TaskItem."],
          ["Defina dados necessários", "Cada componente precisa saber quais informações recebe."],
        ),
        example: {
          label: "Quebra visual",
          code: [
            "App",
            "- Header",
            "- ProductList",
            "  - ProductCard",
            "  - ProductCard",
            "- Footer",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Pegue uma página de portfólio e liste quais componentes ela teria.",
          expected: "Exemplo: Hero, ProjectCard, SkillsList, ContactForm.",
          pitfalls: ["Criar componente para cada palavra", "Não separar repetição", "Nomear de forma genérica"],
        },
        quiz: [
          {
            question: "Componente é:",
            options: ["Parte reutilizável da interface", "Um deploy", "Um banco de dados", "Um erro"],
            answer: 0,
            explanation: "Componentes ajudam a organizar e reutilizar UI.",
          },
          {
            question: "ProductCard é bom nome porque:",
            options: ["Explica o papel do componente", "É curto apenas", "Não diz nada", "É obrigatório"],
            answer: 0,
            explanation: "Nome semântico facilita entender a estrutura.",
          },
        ],
      }),
      makeLesson({
        id: "props-dados",
        title: "Props como dados de entrada",
        time: "22 min",
        difficulty: "Nível 26",
        objective: "Entender props como entradas de um componente.",
        reading: [
          "Props são dados que um componente recebe de fora. Pense nelas como parâmetros de função.",
          "Se uma função recebe nome e retorna saudação, um componente recebe title e price e renderiza um card.",
          "Entender props fica fácil quando você domina entrada, processamento e saída.",
        ],
        concepts: ["Props", "Entrada", "Renderização", "Dados"],
        steps: makeSteps(
          ["Defina o dado", "O que o componente precisa receber?"],
          ["Use na renderização", "Mostre a prop no lugar certo da UI."],
          ["Reutilize", "Chame o mesmo componente com dados diferentes."],
        ),
        example: {
          label: "Card com dados",
          code: [
            "function ProductCard({ nome, preco }) {",
            "  return `<article>${nome} - R$ ${preco}</article>`;",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Descreva quais props um ProjectCard de portfólio deveria receber.",
          expected: "Inclua título, descrição, stack, link e imagem.",
          pitfalls: ["Colocar dados fixos demais", "Não pensar em reuso", "Misturar props com estado"],
        },
        quiz: [
          {
            question: "Props se parecem com:",
            options: ["Parâmetros de função", "CSS global", "Loop infinito", "Erro de deploy"],
            answer: 0,
            explanation: "Props são entradas usadas pelo componente.",
          },
          {
            question: "Por que props ajudam no reuso?",
            options: ["Mesmo componente pode receber dados diferentes", "Elas apagam HTML", "Elas substituem lógica", "Elas impedem arrays"],
            answer: 0,
            explanation: "O componente mantém estrutura e troca conteúdo por dados.",
          },
        ],
      }),
      makeLesson({
        id: "estado-ui",
        title: "Estado da interface",
        time: "24 min",
        difficulty: "Nível 27",
        objective: "Entender estado como memória atual da tela.",
        reading: [
          "Estado é a memória da interface: aba ativa, modal aberto, texto digitado, tarefas concluídas, carrinho atual.",
          "Quando o estado muda, a interface precisa refletir essa mudança.",
          "React formaliza esse padrão com useState, mas a ideia já existe em JavaScript puro: uma variável muda e você renderiza novamente.",
        ],
        concepts: ["Estado", "Atualização", "Renderização", "Interação"],
        steps: makeSteps(
          ["Identifique o que muda", "Nem tudo é estado. Estado é o que pode variar com interação."],
          ["Atualize com ação", "Clique, submit ou input mudam o valor."],
          ["Reflita na tela", "Renderize novamente ou altere o DOM."],
        ),
        example: {
          label: "Aba ativa",
          code: [
            "let abaAtiva = 'home';",
            "function trocarAba(novaAba) {",
            "  abaAtiva = novaAba;",
            "  console.log('Aba atual: ' + abaAtiva);",
            "}",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática",
          prompt: "Liste três estados possíveis de um app de estudos como Logic Quest.",
          expected: "Exemplos: lição ativa, progresso, modal aberto, resposta selecionada.",
          pitfalls: ["Chamar texto fixo de estado", "Não ligar estado à interação", "Misturar estado com estilo estático"],
        },
        quiz: [
          {
            question: "Estado representa:",
            options: ["Memória atual da interface", "Apenas HTML", "A cor fixa", "Nome do repositório"],
            answer: 0,
            explanation: "Estado muda conforme o usuário interage.",
          },
          {
            question: "Quando estado muda, a UI deve:",
            options: ["Refletir a mudança", "Sumir sempre", "Ignorar o usuário", "Parar o app"],
            answer: 0,
            explanation: "A tela precisa mostrar a nova realidade do app.",
          },
        ],
      }),
      makeLesson({
        id: "projeto-final",
        title: "Projeto final: lógica aplicada",
        time: "35 min",
        difficulty: "Nível 28",
        objective: "Planejar e construir um mini app usando tudo que foi aprendido.",
        reading: [
          "O objetivo final não é acertar quiz. É sair capaz de construir. Por isso, o projeto final junta dados, condição, função, array, estado e renderização.",
          "Escolha um mini app: calculadora de IMC, to-do list, controle de gastos, quiz simples ou carrinho de compras.",
          "Antes de codar, escreva entrada, regras, saída, estado, funções e renderização. Depois implemente em partes pequenas.",
        ],
        concepts: ["Projeto", "Planejamento", "Implementação", "Entrega"],
        steps: makeSteps(
          ["Planeje o fluxo", "Defina entrada, processamento, saída e estado."],
          ["Implemente em partes", "Comece pelos dados, depois funções, depois eventos e renderização."],
          ["Teste cenários", "Teste sucesso, erro, vazio e limite."],
        ),
        example: {
          label: "Checklist de entrega",
          code: [
            "1. Quais dados entram?",
            "2. Quais regras existem?",
            "3. Qual estado muda?",
            "4. Quais funções preciso criar?",
            "5. Como a tela será atualizada?",
            "6. Quais erros preciso tratar?",
          ].join("\n"),
        },
        drill: {
          title: "Missão prática final",
          prompt: "Escolha um mini app e escreva o plano técnico completo. Depois implemente a primeira versão no Playground ou no VS Code.",
          expected: "O plano precisa citar entrada, processamento, saída, estado, funções, eventos e testes.",
          pitfalls: ["Abrir o editor sem plano", "Fazer tudo de uma vez", "Não testar casos de erro"],
        },
        quiz: [
          {
            question: "Antes de começar um projeto, você deve:",
            options: ["Planejar entrada, regra, saída e estado", "Copiar qualquer template", "Escolher animação primeiro", "Ignorar testes"],
            answer: 0,
            explanation: "Planejamento reduz retrabalho e guia a implementação.",
          },
          {
            question: "Um bom mini app para treinar lógica deve ter:",
            options: ["Dados, regra, interação e saída", "Só imagem", "Só CSS", "Apenas README"],
            answer: 0,
            explanation: "Esses elementos obrigam você a programar de verdade.",
          },
        ],
      }),
    ],
  },
];
